ACCESS_TOKEN_COOKIE = "bf_access"
REFRESH_TOKEN_COOKIE = "bf_refresh"

OTP_PURPOSE_LOGIN = "login"
OTP_PURPOSE_VERIFY_PHONE = "verify_phone"

OTP_LENGTH = 4
OTP_EXPIRE_MINUTES = 5
OTP_MAX_ATTEMPTS = 5
OTP_RESEND_COOLDOWN_SECONDS = 60
OTP_RATE_LIMIT_PER_PHONE = 5
OTP_RATE_LIMIT_WINDOW_SECONDS = 900

ACCESS_TOKEN_EXPIRE_MINUTES = 15
REFRESH_TOKEN_EXPIRE_DAYS = 30

PASSWORD_RESET_EXPIRE_HOURS = 1
EMAIL_VERIFY_EXPIRE_HOURS = 24

AUTH_ROUTER_PREFIX = "/auth"
