-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = e0000000-0000-4000-8000-000000000003

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'e0000000-0000-4000-8000-000000000003'
);
DELETE FROM module_scores WHERE attempt_id IN (
  SELECT id FROM test_attempts WHERE mock_test_id = 'e0000000-0000-4000-8000-000000000003'
);
DELETE FROM test_attempts WHERE mock_test_id = 'e0000000-0000-4000-8000-000000000003';
DELETE FROM questions WHERE mock_test_id = 'e0000000-0000-4000-8000-000000000003';

INSERT INTO mock_tests (id, title, description, is_published)
VALUES (
  'e0000000-0000-4000-8000-000000000003',
  'IELTS Listening — Tutorial Discussion — Reviewing a Student Research Proposal',
  'Founder Section 3: Tutorial Discussion — Reviewing a Student Research Proposal. Source: ielts_listening_section_3. Audio: listening/bandforge-s3/part-1/full.mp3.',
  true
)
ON CONFLICT (id) DO UPDATE
SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  is_published = true;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'mcq', 1, 'Which TWO weaknesses does the tutor identify in the students'' draft proposal?', 'Choose TWO letters, A-E.', 'listening/bandforge-s3/part-1/full.mp3', '[{"label": "A", "text": "The research question is too broad."}, {"label": "B", "text": "The sample is not large enough."}, {"label": "C", "text": "The proposed timeline is too tight."}, {"label": "D", "text": "The two variables may be difficult to separate."}, {"label": "E", "text": "It relies too heavily on students reporting their own grades."}]'::jsonb, 'A', 'detail'),
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'mcq', 2, 'Which TWO weaknesses does the tutor identify in the students'' draft proposal?', NULL, 'listening/bandforge-s3/part-1/full.mp3', '[{"label": "A", "text": "The research question is too broad."}, {"label": "B", "text": "The sample is not large enough."}, {"label": "C", "text": "The proposed timeline is too tight."}, {"label": "D", "text": "The two variables may be difficult to separate."}, {"label": "E", "text": "It relies too heavily on students reporting their own grades."}]'::jsonb, 'E', 'detail'),
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'mcq', 3, 'Which TWO changes do the students decide to make to their proposal?', 'Choose TWO letters, A-E.', 'listening/bandforge-s3/part-1/full.mp3', '[{"label": "A", "text": "carry out a pilot study first"}, {"label": "B", "text": "narrow the focus to a single department"}, {"label": "C", "text": "lengthen the data-collection period"}, {"label": "D", "text": "increase the number of participants"}, {"label": "E", "text": "obtain grade data directly from the university"}]'::jsonb, 'B', 'detail'),
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'mcq', 4, 'Which TWO changes do the students decide to make to their proposal?', NULL, 'listening/bandforge-s3/part-1/full.mp3', '[{"label": "A", "text": "carry out a pilot study first"}, {"label": "B", "text": "narrow the focus to a single department"}, {"label": "C", "text": "lengthen the data-collection period"}, {"label": "D", "text": "increase the number of participants"}, {"label": "E", "text": "obtain grade data directly from the university"}]'::jsonb, 'E', 'detail'),
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'mcq', 5, 'Which part of the proposal does the tutor consider the strongest?', 'Choose the correct letter, A, B or C.', 'listening/bandforge-s3/part-1/full.mp3', '[{"label": "A", "text": "the originality of the topic"}, {"label": "B", "text": "the review of earlier studies"}, {"label": "C", "text": "the plan for analysing the data"}]'::jsonb, 'B', 'detail'),
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'sentence_completion', 6, 'The students will define long working hours as more than ___ hours per week.', 'Complete the sentences below. Write NO MORE THAN TWO WORDS for each answer.', 'listening/bandforge-s3/part-1/full.mp3', NULL, 'fifteen', 'completion'),
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'sentence_completion', 7, 'Academic performance will be measured using students'' end-of- ___ results.', NULL, 'listening/bandforge-s3/part-1/full.mp3', NULL, 'semester', 'completion'),
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'sentence_completion', 8, 'All participant responses must be kept ___ .', NULL, 'listening/bandforge-s3/part-1/full.mp3', NULL, 'anonymous', 'completion'),
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'sentence_completion', 9, 'The students plan to present their early findings at a department ___ .', NULL, 'listening/bandforge-s3/part-1/full.mp3', NULL, 'seminar', 'completion'),
('e0000000-0000-4000-8000-000000000003', 'listening', 1, 'sentence_completion', 10, 'The tutor advises including a section on the ___ of the study in the final write-up.', NULL, 'listening/bandforge-s3/part-1/full.mp3', NULL, 'limitations', 'completion');
