-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000002

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'listening' AND part = 3
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'listening' AND part = 3;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'mcq', 1, 'Which TWO problems did the students have with their data collection?', 'Choose TWO letters, A–E.', 'listening/m02/part-3/full.mp3', '[{"label": "A", "text": "Not enough people responded."}, {"label": "B", "text": "Some questions were unclear."}, {"label": "C", "text": "The survey was too long."}, {"label": "D", "text": "They could not visit all the locations they had planned."}, {"label": "E", "text": "The weather disrupted their fieldwork."}]'::jsonb, 'B', 'detail'),
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'mcq', 2, 'Which TWO problems did the students have with their data collection?', NULL, 'listening/m02/part-3/full.mp3', '[{"label": "A", "text": "Not enough people responded."}, {"label": "B", "text": "Some questions were unclear."}, {"label": "C", "text": "The survey was too long."}, {"label": "D", "text": "They could not visit all the locations they had planned."}, {"label": "E", "text": "The weather disrupted their fieldwork."}]'::jsonb, 'D', 'detail'),
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'mcq', 3, 'Which TWO sources does the tutor advise the students to use?', 'Choose TWO letters, A–E.', 'listening/m02/part-3/full.mp3', '[{"label": "A", "text": "government transport statistics"}, {"label": "B", "text": "interviews with transport staff"}, {"label": "C", "text": "a dissertation by a previous student"}, {"label": "D", "text": "local newspaper reports"}, {"label": "E", "text": "a journal article on commuting"}]'::jsonb, 'A', 'detail'),
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'mcq', 4, 'Which TWO sources does the tutor advise the students to use?', NULL, 'listening/m02/part-3/full.mp3', '[{"label": "A", "text": "government transport statistics"}, {"label": "B", "text": "interviews with transport staff"}, {"label": "C", "text": "a dissertation by a previous student"}, {"label": "D", "text": "local newspaper reports"}, {"label": "E", "text": "a journal article on commuting"}]'::jsonb, 'C', 'detail'),
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'mcq', 5, 'What does the tutor consider the main strength of the project?', 'Choose the correct letter, A, B or C.', 'listening/m02/part-3/full.mp3', '[{"label": "A", "text": "the originality of the topic"}, {"label": "B", "text": "the clear presentation of the findings"}, {"label": "C", "text": "the size of the sample"}]'::jsonb, 'B', 'detail'),
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'sentence_completion', 6, 'The report will be reorganised around three main ___ .', 'Complete the sentences below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.', 'listening/m02/part-3/full.mp3', NULL, 'themes', 'completion'),
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'sentence_completion', 7, 'Maya will write the ___ section of the report.', NULL, 'listening/m02/part-3/full.mp3', NULL, 'methodology', 'completion'),
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'sentence_completion', 8, 'Tom must redraw the charts so that readers can ___ them easily.', NULL, 'listening/m02/part-3/full.mp3', NULL, 'interpret', 'completion'),
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'sentence_completion', 9, 'The literature review should be no more than ___ words long.', NULL, 'listening/m02/part-3/full.mp3', NULL, '800/eight hundred', 'completion'),
('a0000000-0000-4000-8000-000000000002', 'listening', 3, 'sentence_completion', 10, 'The students must give their draft to the tutor by the ___ of May.', NULL, 'listening/m02/part-3/full.mp3', NULL, 'twelfth/12th', 'completion');
