-- BandForge reading seed: The Psychology of Leadership in Times of Crisis
-- mock_test_id = a0000000-0000-4000-8000-000000000002 part = 3

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 3
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 3;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 1, 3, 'Citizens always form an accurate picture of their leaders during a crisis.', 'The Psychology of Leadership in Times of Crisis

A    When a nation faces sudden danger — a war, an economic collapse, a pandemic — public attention turns sharply towards those in charge. Citizens expect their leaders to act with clarity and resolve, and historians often judge a presidency or premiership by its conduct during such moments. Yet the psychological reality of leading under crisis is considerably more complicated than the popular image of the calm, all-seeing decision-maker suggests. Crises do not merely test character; they distort the conditions under which judgement is exercised, compressing the time available for reflection and raising the stakes of every choice. Understanding how leaders actually behave under such pressure has therefore become a significant concern for political psychologists. Their work draws on historical case studies, interviews, and controlled experiments, and it consistently challenges the assumption that good leadership in a crisis is simply a matter of strength of will.

B    One of the most consistent findings is that acute stress narrows the range of options a leader is able to consider. Under pressure, decision-making tends to become faster but also more rigid, with individuals relying on familiar assumptions rather than seeking fresh information. This tendency is intensified within small groups of advisers. In 1972 the psychologist Irving Janis introduced the term "groupthink" to describe how cohesive teams, anxious to preserve unity, can suppress dissent and converge prematurely on a flawed course of action. His central example was the 1961 decision by the United States government to support an invasion of Cuba at the Bay of Pigs — a plan whose obvious weaknesses went unchallenged because no adviser wished to appear disloyal. Janis argued that the problem was not a lack of intelligence among those involved, but a social atmosphere in which doubt felt inappropriate.

C    Crisis leadership is not only a matter of private decision-making; it is also, perhaps above all, an exercise in public communication. A leader''s words can either steady a frightened population or deepen its alarm. Research into political rhetoric suggests that audiences respond less to the technical content of a message than to the impression of competence and sincerity it conveys. During the economic emergency of the 1930s, the broadcasts of the American president Franklin Roosevelt were widely credited with restoring public confidence, not because they offered detailed policy but because they projected steadiness and candour. The lesson drawn by later scholars was that the management of emotion is as central to crisis leadership as the management of events.

D    A more troubling pattern concerns the projection of certainty. Because populations crave reassurance, leaders are rewarded for appearing confident, even when the situation is genuinely unclear. This creates an incentive to overstate what is known and to understate what is not. The political scientist Philip Tetlock, in a long study of expert forecasting, found that confident, decisive predictions were no more accurate than cautious ones — and were often less so — yet they consistently attracted more attention and trust. Applied to crisis leadership, this finding implies a hidden cost: the very assurance that calms the public in the short term may discourage the honest revision of policy when circumstances change.

E    It is tempting to assume that emergencies reveal a leader''s "true self", or even that they create new qualities under pressure. The evidence points instead to amplification. Crises rarely transform personality; more often they exaggerate dispositions that were already present. A leader inclined towards caution becomes more hesitant, while one prone to boldness becomes more reckless. For this reason, psychologists who study political behaviour place considerable weight on a leader''s record before a crisis arrives, treating it as a better guide to likely conduct than any promise made once danger is at hand. This is one reason why sudden shifts in a leader''s behaviour during a crisis are often viewed by researchers with scepticism rather than admiration.', '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 2, 3, 'Stress makes leaders consider a wider range of options.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 3, 3, 'Groupthink was first described using the Bay of Pigs invasion as an example.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 4, 3, 'Roosevelt''s broadcasts succeeded because they explained policy in technical detail.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 5, 3, 'Tetlock found that confident forecasts were usually more accurate.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 6, 3, 'Paragraph B', NULL, '[{"label": "i", "text": "How stress alters private decision-making"}, {"label": "ii", "text": "Why advisers may fail to challenge a leader"}, {"label": "iii", "text": "The role of public speaking during emergencies"}, {"label": "iv", "text": "The temptation to appear more certain than the facts allow"}, {"label": "v", "text": "Why earlier behaviour may predict crisis conduct"}, {"label": "vi", "text": "The advantages of calm leadership"}, {"label": "vii", "text": "How historians judge failed policies"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 7, 3, 'Paragraph C', NULL, '[{"label": "i", "text": "How stress alters private decision-making"}, {"label": "ii", "text": "Why advisers may fail to challenge a leader"}, {"label": "iii", "text": "The role of public speaking during emergencies"}, {"label": "iv", "text": "The temptation to appear more certain than the facts allow"}, {"label": "v", "text": "Why earlier behaviour may predict crisis conduct"}, {"label": "vi", "text": "The advantages of calm leadership"}, {"label": "vii", "text": "How historians judge failed policies"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 8, 3, 'Paragraph D', NULL, '[{"label": "i", "text": "How stress alters private decision-making"}, {"label": "ii", "text": "Why advisers may fail to challenge a leader"}, {"label": "iii", "text": "The role of public speaking during emergencies"}, {"label": "iv", "text": "The temptation to appear more certain than the facts allow"}, {"label": "v", "text": "Why earlier behaviour may predict crisis conduct"}, {"label": "vi", "text": "The advantages of calm leadership"}, {"label": "vii", "text": "How historians judge failed policies"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 9, 3, 'Paragraph E', NULL, '[{"label": "i", "text": "How stress alters private decision-making"}, {"label": "ii", "text": "Why advisers may fail to challenge a leader"}, {"label": "iii", "text": "The role of public speaking during emergencies"}, {"label": "iv", "text": "The temptation to appear more certain than the facts allow"}, {"label": "v", "text": "Why earlier behaviour may predict crisis conduct"}, {"label": "vi", "text": "The advantages of calm leadership"}, {"label": "vii", "text": "How historians judge failed policies"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 10, 3, 'Irving Janis introduced the term ______ in 1972.', NULL, NULL, 'groupthink', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 11, 3, 'During the 1930s, ______ broadcast to restore public confidence.', NULL, NULL, 'Roosevelt/Franklin Roosevelt', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 12, 3, 'Tetlock found that bold predictions attracted more ______.', NULL, NULL, 'trust/attention', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 13, 3, 'Crises tend to ______ existing personality traits.', NULL, NULL, 'amplify/exaggerate', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 14, 3, 'Sudden changes in a leader''s behaviour are often viewed with ______.', NULL, NULL, 'scepticism/skepticism', 'sentence_completion');
