-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000002

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'listening' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'listening' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'sentence_completion', 1, 'The reserve was created on land that was previously a ___ .', 'Complete the sentences below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.', 'listening/m02/part-2/full.mp3', NULL, 'gravel pit', 'completion'),
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'sentence_completion', 2, 'The reserve now covers a total of ___ hectares.', NULL, 'listening/m02/part-2/full.mp3', NULL, 'sixty/60', 'completion'),
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'sentence_completion', 3, 'The boardwalk across the marsh is built from recycled ___ .', NULL, 'listening/m02/part-2/full.mp3', NULL, 'plastic', 'completion'),
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'sentence_completion', 4, 'Visitors may borrow ___ from reception without paying.', NULL, 'listening/m02/part-2/full.mp3', NULL, 'binoculars', 'completion'),
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'sentence_completion', 5, 'The food served in the café is made largely with ___ ingredients.', NULL, 'listening/m02/part-2/full.mp3', NULL, 'local', 'completion'),
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'mcq', 6, 'From the new lookout tower, visitors can reliably see', 'Choose the correct letter, A, B or C.', 'listening/m02/part-2/full.mp3', '[{"label": "A", "text": "rare ducks"}, {"label": "B", "text": "nesting ospreys"}, {"label": "C", "text": "deer"}]'::jsonb, 'C', 'detail'),
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'mcq', 7, 'The guide says the best time to visit the reedbed is', NULL, 'listening/m02/part-2/full.mp3', '[{"label": "A", "text": "early in the morning"}, {"label": "B", "text": "around midday"}, {"label": "C", "text": "in the late afternoon"}]'::jsonb, 'A', 'detail'),
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'mcq', 8, 'Visitors to the reserve are asked not to', NULL, 'listening/m02/part-2/full.mp3', '[{"label": "A", "text": "bring dogs with them"}, {"label": "B", "text": "cycle on the paths"}, {"label": "C", "text": "feed the birds"}]'::jsonb, 'C', 'detail'),
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'mcq', 9, 'This year, the photography exhibition is located in', NULL, 'listening/m02/part-2/full.mp3', '[{"label": "A", "text": "the visitor centre"}, {"label": "B", "text": "the old barn"}, {"label": "C", "text": "the café"}]'::jsonb, 'B', 'detail'),
('a0000000-0000-4000-8000-000000000002', 'listening', 2, 'mcq', 10, 'The main new feature at the reserve this year is', NULL, 'listening/m02/part-2/full.mp3', '[{"label": "A", "text": "a children''s play area"}, {"label": "B", "text": "a wheelchair-accessible trail"}, {"label": "C", "text": "a gift shop"}]'::jsonb, 'B', 'detail');
