-- BandForge reading seed: The Unfulfilled Promise of Educational Technology
-- mock_test_id = a0000000-0000-4000-8000-000000000002 part = 2

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 1, 2, 'Thomas Edison predicted that motion pictures would replace textbooks.', 'The Unfulfilled Promise of Educational Technology

A    For more than a century, each new communication technology has arrived in classrooms accompanied by bold predictions. In the 1920s, the inventor Thomas Edison declared that motion pictures would soon replace textbooks; later, radio, television, and the personal computer were each described as forces that would transform how children learn. The pattern has been remarkably consistent: an initial wave of enthusiasm, followed by disappointment as the new tool fails to deliver the promised revolution. Understanding why this cycle repeats has become an important question for researchers, particularly as digital devices now occupy a central place in schools worldwide. The mismatch between confident forecasts and actual classroom results raises a deeper issue: whether the problem lies in the technology itself, or in the assumptions made about what it can achieve.

B    The most recent example of this cycle is the massive open online course, or MOOC. When platforms such as Coursera and edX were launched in 2012, commentators described that period as the "year of the MOOC" and predicted that free, university-level courses would make traditional institutions obsolete. Enrolment figures were indeed enormous, with individual courses attracting hundreds of thousands of registrations. Yet completion told a different story. A widely cited analysis by researchers at the University of Pennsylvania found that, on average, only about four per cent of those who signed up for a course finished it. Most participants, moreover, already held a degree, suggesting that the courses were extending opportunity for the well-educated rather than reaching new learners. By the end of the decade, most universities had quietly accepted that MOOCs would complement campus teaching rather than replace it.

C    Similar gaps between expectation and outcome have appeared in schools. Many governments have invested heavily in schemes to provide every pupil with a laptop or tablet, on the assumption that access to devices would automatically raise achievement. The evidence has been mixed at best. A large 2015 report by the Organisation for Economic Co-operation and Development examined data from dozens of countries and concluded that students who used computers very frequently at school tended to perform worse in reading and mathematics, even after social background was taken into account. The report did not argue that technology was harmful in itself, but it questioned the belief that simply distributing hardware would improve results. What mattered, the authors suggested, was not whether computers were present but how, and how often, they were used.

D    Researchers who study these failures point to a recurring misunderstanding. Technology, they argue, is not a substitute for skilled teaching; it is a tool whose value depends entirely on how it is used. A tablet can display an excellent lesson or a poor one, and a pupil left alone with a device may simply become distracted. There is also evidence of a so-called second digital divide. While access to devices has become more equal, the ability to use them productively has not. Students from advantaged homes are more likely to use technology for learning, whereas those from poorer backgrounds more often use the same devices for entertainment, which can widen rather than narrow existing gaps in attainment.

E    None of this means that technology has no place in education. When it is carefully designed and closely integrated with teaching, it can produce genuine benefits. Adaptive learning software, which adjusts the difficulty of questions to each learner''s performance, has shown modest but consistent gains in subjects such as mathematics. The underlying idea is old: in 1984 the psychologist Benjamin Bloom observed that a student receiving one-to-one tutoring could outperform around ninety-eight per cent of pupils taught in conventional classes, a result he called the "two sigma problem". Personalised software cannot fully reproduce a human tutor, but it can offer some of the individual attention that large classes make impossible. Crucially, the most successful programmes are not those that replace teachers but those that support them — adjusting content while keeping a human adult in charge of motivation and discipline. As long as schools focus narrowly on hardware adoption rather than on training teachers to use tools well, the cycle of promise and disappointment is likely to continue.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 2, 2, 'On average only about four per cent of MOOC enrollees completed their courses.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 3, 2, 'The 2015 OECD report argued that classroom computers were harmful in themselves.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 4, 2, 'Students from poorer backgrounds often use technology mainly for entertainment.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 5, 2, 'Benjamin Bloom claimed that one-to-one tutoring could help ninety-eight per cent of pupils outperform their classmates.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 6, 2, 'Paragraph B', NULL, '[{"label": "i", "text": "High enrolment but low completion"}, {"label": "ii", "text": "Hardware alone does not raise standards"}, {"label": "iii", "text": "Technology depends on how teachers use it"}, {"label": "iv", "text": "A second form of inequality in digital access"}, {"label": "v", "text": "When software can approximate individual teaching"}, {"label": "vi", "text": "Why governments prefer laptops to textbooks"}, {"label": "vii", "text": "The role of radio in early classrooms"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 7, 2, 'Paragraph C', NULL, '[{"label": "i", "text": "High enrolment but low completion"}, {"label": "ii", "text": "Hardware alone does not raise standards"}, {"label": "iii", "text": "Technology depends on how teachers use it"}, {"label": "iv", "text": "A second form of inequality in digital access"}, {"label": "v", "text": "When software can approximate individual teaching"}, {"label": "vi", "text": "Why governments prefer laptops to textbooks"}, {"label": "vii", "text": "The role of radio in early classrooms"}]'::jsonb, 'ii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 8, 2, 'Paragraph D', NULL, '[{"label": "i", "text": "High enrolment but low completion"}, {"label": "ii", "text": "Hardware alone does not raise standards"}, {"label": "iii", "text": "Technology depends on how teachers use it"}, {"label": "iv", "text": "A second form of inequality in digital access"}, {"label": "v", "text": "When software can approximate individual teaching"}, {"label": "vi", "text": "Why governments prefer laptops to textbooks"}, {"label": "vii", "text": "The role of radio in early classrooms"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 9, 2, 'Paragraph E', NULL, '[{"label": "i", "text": "High enrolment but low completion"}, {"label": "ii", "text": "Hardware alone does not raise standards"}, {"label": "iii", "text": "Technology depends on how teachers use it"}, {"label": "iv", "text": "A second form of inequality in digital access"}, {"label": "v", "text": "When software can approximate individual teaching"}, {"label": "vi", "text": "Why governments prefer laptops to textbooks"}, {"label": "vii", "text": "The role of radio in early classrooms"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 10, 2, 'Coursera and edX were launched in ______.', NULL, NULL, '2012', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 11, 2, 'Bloom described the tutoring gap as the ______ problem.', NULL, NULL, 'two sigma', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 12, 2, 'The OECD report on school computers was published in ______.', NULL, NULL, '2015', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 13, 2, 'The most successful programmes support teachers rather than ______ them.', NULL, NULL, 'replacing/replace', 'sentence_completion');
