-- BandForge reading seed: The Architecture of Prevention: Rethinking Public Health Systems
-- mock_test_id = a0000000-0000-4000-8000-000000000003 part = 1

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'reading' AND part = 1
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'reading' AND part = 1;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 1, 1, 'McGinnis and Foege concluded that approximately half of all premature deaths in the US were linked to factors that could potentially be modified.', 'The Architecture of Prevention: Rethinking Public Health Systems

A    For much of the twentieth century, the dominant model of healthcare in industrialised nations was built around the treatment of illness rather than its prevention. Hospitals and specialist clinics absorbed the majority of public health expenditure, while programmes designed to reduce the incidence of disease in the first place were chronically underfunded. This imbalance began to attract serious academic scrutiny in the 1990s, when a landmark study by McGinnis and Foege, published in the Journal of the American Medical Association in 1993, estimated that nearly half of all premature deaths in the United States could be attributed to modifiable behavioural and environmental factors — conditions that preventive care was uniquely positioned to address. The study''s conclusions challenged the assumption that clinical medicine alone could carry the burden of a nation''s health.

B    The economic case for shifting resources towards preventive care is compelling, though not without nuance. A frequently cited analysis by the Trust for America''s Health found that investing ten dollars per person annually in community-based prevention programmes could generate a return of more than five dollars for every dollar spent within five years, primarily through reduced hospitalisation rates and lower demand for emergency services. However, critics have noted that such projections often rely on optimistic assumptions about programme uptake and population compliance. Preventive interventions, unlike surgical procedures, produce their benefits diffusely and over extended time horizons, making it politically difficult to justify their cost in legislative budgeting cycles that rarely extend beyond four years.

C    Primary care networks have emerged as the most practicable vehicle for delivering preventive services at scale. In countries such as the United Kingdom, where the National Health Service operates an extensive general practitioner system, preventive consultations — including screening for cardiovascular disease, type 2 diabetes, and certain cancers — are embedded within routine healthcare contacts. Research published in The Lancet in 2017 by Kringos and colleagues demonstrated that nations with stronger primary care infrastructure recorded significantly lower rates of avoidable hospital admissions, a key indicator of preventive care effectiveness. The study, which analysed data from thirty-one European countries, found that the strength of a nation''s primary care system was the single most consistent predictor of population health outcomes, outperforming both GDP per capita and total healthcare expenditure.

D    Yet the capacity of primary care to fulfil a preventive function is constrained by structural pressures that are common across healthcare systems. Consultations are short — typically under fifteen minutes in high-income countries — and clinicians frequently prioritise acute presentations over longer-term preventive conversations. Furthermore, the social determinants of health, including income inequality, housing conditions, and educational attainment, lie largely beyond the reach of clinical intervention. Research consistently shows that individuals from lower socioeconomic backgrounds are both less likely to engage with preventive services and more likely to experience the chronic conditions that such services are designed to forestall. This creates a paradox sometimes referred to as the inverse care law: the availability of good medical care tends to vary inversely with the need for it in the population served.

E    Community health workers have gained recognition as a means of bridging the gap between formal health systems and the populations they most struggle to reach. Deployed in countries as diverse as Brazil, Ethiopia, and Bangladesh, community health workers operate outside clinical settings, conducting household visits, providing basic health education, and connecting individuals to formal services. Brazil''s Family Health Programme, launched in 1994, is among the most extensively evaluated examples: by 2010, the programme had achieved coverage of more than half the national population, and studies attributed to it a significant reduction in infant mortality and hospitalisation rates for conditions amenable to primary care. The model''s success has prompted the World Health Organisation to recommend community health worker integration as a core strategy in national health plans.

F    Digital technology has introduced new possibilities for preventive health delivery, though its potential remains unevenly distributed. Mobile health applications, electronic screening reminders, and telehealth consultations have enabled preventive contacts that were previously limited by geography and infrastructure. In low- and middle-income countries, mobile phone penetration has, in some instances, outpaced the availability of traditional health facilities, creating an opportunity to reach populations that formal systems have historically bypassed. Nevertheless, the evidence base for digital preventive health interventions remains mixed. A systematic review conducted by Marcolino and colleagues in 2018 found that while mobile health tools produced modest improvements in medication adherence and chronic disease monitoring, their impact on the upstream determinants of disease — behaviour change and structural risk factors — was inconsistent and difficult to sustain.

G    The broader argument for investing in preventive public health systems ultimately rests on a reconceptualisation of what healthcare is for. A system oriented around prevention does not merely treat the sick; it seeks to reduce the number of people who become sick in the first place. This shift requires sustained political commitment, cross-sectoral collaboration between health, education, and housing authorities, and a willingness to measure success over decades rather than electoral cycles. The evidence accumulated over the past thirty years suggests that the capacity to prevent disease already exists. The challenge is not scientific but political and institutional — a matter of converting knowledge into sustained action.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 2, 1, 'The Trust for America''s Health study found that preventive investment would generate savings within the first two years of implementation.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 3, 1, 'The Kringos study examined data from fewer than thirty European countries.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 4, 1, 'In the United Kingdom, preventive consultations for type 2 diabetes are included in routine general practitioner appointments.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 5, 1, 'Community health workers in Brazil are required to hold a formal nursing qualification before deployment.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NOT GIVEN', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 6, 1, 'Paragraph B', NULL, '[{"label": "i", "text": "The financial rationale for disease prevention and the limits of its projections"}, {"label": "ii", "text": "How technological advances have transformed clinical treatment"}, {"label": "iii", "text": "The use of non-clinical workers to extend preventive reach"}, {"label": "iv", "text": "Evidence that stronger primary care reduces avoidable hospital stays"}, {"label": "v", "text": "The political obstacles to long-term health planning"}, {"label": "vi", "text": "The inherent tensions within primary care as a preventive setting"}, {"label": "vii", "text": "International comparisons of disease screening uptake"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 7, 1, 'Paragraph C', NULL, '[{"label": "i", "text": "The financial rationale for disease prevention and the limits of its projections"}, {"label": "ii", "text": "How technological advances have transformed clinical treatment"}, {"label": "iii", "text": "The use of non-clinical workers to extend preventive reach"}, {"label": "iv", "text": "Evidence that stronger primary care reduces avoidable hospital stays"}, {"label": "v", "text": "The political obstacles to long-term health planning"}, {"label": "vi", "text": "The inherent tensions within primary care as a preventive setting"}, {"label": "vii", "text": "International comparisons of disease screening uptake"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 8, 1, 'Paragraph D', NULL, '[{"label": "i", "text": "The financial rationale for disease prevention and the limits of its projections"}, {"label": "ii", "text": "How technological advances have transformed clinical treatment"}, {"label": "iii", "text": "The use of non-clinical workers to extend preventive reach"}, {"label": "iv", "text": "Evidence that stronger primary care reduces avoidable hospital stays"}, {"label": "v", "text": "The political obstacles to long-term health planning"}, {"label": "vi", "text": "The inherent tensions within primary care as a preventive setting"}, {"label": "vii", "text": "International comparisons of disease screening uptake"}]'::jsonb, 'vi', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 9, 1, 'Paragraph E', NULL, '[{"label": "i", "text": "The financial rationale for disease prevention and the limits of its projections"}, {"label": "ii", "text": "How technological advances have transformed clinical treatment"}, {"label": "iii", "text": "The use of non-clinical workers to extend preventive reach"}, {"label": "iv", "text": "Evidence that stronger primary care reduces avoidable hospital stays"}, {"label": "v", "text": "The political obstacles to long-term health planning"}, {"label": "vi", "text": "The inherent tensions within primary care as a preventive setting"}, {"label": "vii", "text": "International comparisons of disease screening uptake"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'sentence_completion', 10, 1, 'Critics of preventive investment argue that cost projections often depend on unrealistic assumptions about ______________ and population compliance.', NULL, NULL, 'programme uptake/program uptake', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'sentence_completion', 11, 1, 'The Kringos study found that the strength of primary care was the most consistent predictor of population health outcomes, performing better than both GDP and total ______________.', NULL, NULL, 'healthcare expenditure', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'sentence_completion', 12, 1, 'The phenomenon known as the ______________ describes how access to quality care tends to be lowest in communities with the greatest need.', NULL, NULL, 'inverse care law', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'sentence_completion', 13, 1, 'A 2018 systematic review found that mobile health tools produced modest gains in ______________ but had inconsistent effects on the upstream determinants of disease.', NULL, NULL, 'medication adherence', 'sentence_completion');
