-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000003

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'listening' AND part = 1
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'listening' AND part = 1;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 1, 'Surname', 'Complete the form below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.

@@form_title@@APEX RECRUITMENT — CANDIDATE REGISTRATION FORM', 'listening/m03/part-1/full.mp3', NULL, 'Chandra', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 2, 'Mobile Number', NULL, 'listening/m03/part-1/full.mp3', NULL, '07941 332 605/07941332605/07941 332605', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 3, 'Email domain', NULL, 'listening/m03/part-1/full.mp3', NULL, 'greenmail', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 4, 'Postcode', NULL, 'listening/m03/part-1/full.mp3', NULL, 'BS14 2RT/BS142RT', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 5, 'Preferred role type', NULL, 'listening/m03/part-1/full.mp3', NULL, 'office administration', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 6, 'Employment basis', NULL, 'listening/m03/part-1/full.mp3', NULL, 'full-time/full time', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 7, 'Availability to start', NULL, 'listening/m03/part-1/full.mp3', NULL, 'immediately', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 8, 'ID document provided', NULL, 'listening/m03/part-1/full.mp3', NULL, 'passport', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 9, 'Minimum salary (per year)', NULL, 'listening/m03/part-1/full.mp3', NULL, '24000/24,000/£24,000/24000', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 1, 'form_completion', 10, 'Referral source', NULL, 'listening/m03/part-1/full.mp3', NULL, 'personal referral', 'completion');
