-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000003

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'listening' AND part = 4
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'listening' AND part = 4;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 1, 'Main driver of global wetland loss ___', 'Complete the table below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.
@@notes_title@@WETLAND CONSERVATION — COMPARATIVE CASE STUDIES', 'listening/m03/part-4/full.mp3', NULL, 'agriculture', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 2, 'Doñana designated a national park in ___', NULL, 'listening/m03/part-4/full.mp3', NULL, '1969/nineteen sixty-nine', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 3, 'Doñana ongoing challenge ___', NULL, 'listening/m03/part-4/full.mp3', NULL, 'water extraction', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 4, 'Doñana key outcome: habitat for ___', NULL, 'listening/m03/part-4/full.mp3', NULL, 'migratory birds/migratory bird', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 5, 'Mesopotamian Marshes: breaching of ___', NULL, 'listening/m03/part-4/full.mp3', NULL, 'drainage embankments', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 6, 'Marsh area re-flooded ___', NULL, 'listening/m03/part-4/full.mp3', NULL, '58%/58 per cent/fifty-eight per cent/58', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 7, 'Return of ___', NULL, 'listening/m03/part-4/full.mp3', NULL, 'otter/smooth-coated otter/smooth coated otter', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 8, 'Muthurajawela primary threat ___', NULL, 'listening/m03/part-4/full.mp3', NULL, 'illegal encroachment', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 9, 'Local communities as ___', NULL, 'listening/m03/part-4/full.mp3', NULL, 'wetland monitors', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 4, 'note_completion', 10, 'Reduction in dumping ___', NULL, 'listening/m03/part-4/full.mp3', NULL, '40%/40 per cent/forty per cent/40', 'completion');
