-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000003

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'listening' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'listening' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 1, '11 ___', 'Label the map below. Write NO MORE THAN TWO WORDS for each answer.', 'listening/m03/part-2/full.mp3', NULL, 'transport hub', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 2, '12 ___', NULL, 'listening/m03/part-2/full.mp3', NULL, 'community park', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 3, '13 ___', NULL, 'listening/m03/part-2/full.mp3', NULL, 'health centre/health center', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 4, '14 ___', NULL, 'listening/m03/part-2/full.mp3', NULL, 'civic library', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 5, '15 ___', NULL, 'listening/m03/part-2/full.mp3', NULL, 'primary school', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 6, '16 ___', NULL, 'listening/m03/part-2/full.mp3', NULL, 'enterprise centre/enterprise center', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 7, '17 ___', NULL, 'listening/m03/part-2/full.mp3', NULL, 'community hall', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 8, '18 ___', NULL, 'listening/m03/part-2/full.mp3', NULL, 'leisure centre/leisure center/sports and leisure centre/sports centre', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 9, '19 ___', NULL, 'listening/m03/part-2/full.mp3', NULL, 'nature reserve', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 2, 'sentence_completion', 10, '20 ___', NULL, 'listening/m03/part-2/full.mp3', NULL, 'public square', 'completion');
