-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000003

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'listening' AND part = 3
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'listening' AND part = 3;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'mcq', 1, 'Which TWO findings from the student survey showed the strongest correlation with heavy social media use?', 'Choose TWO letters, A–E.', 'listening/m03/part-3/full.mp3', '[{"label": "A", "text": "increased anxiety"}, {"label": "B", "text": "sleep disruption"}, {"label": "C", "text": "reduced social interaction"}, {"label": "D", "text": "academic motivation"}, {"label": "E", "text": "lower physical activity"}]'::jsonb, 'B', 'detail'),
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'mcq', 2, 'Which TWO findings from the student survey showed the strongest correlation with heavy social media use?', NULL, 'listening/m03/part-3/full.mp3', '[{"label": "A", "text": "increased anxiety"}, {"label": "B", "text": "sleep disruption"}, {"label": "C", "text": "reduced social interaction"}, {"label": "D", "text": "academic motivation"}, {"label": "E", "text": "lower physical activity"}]'::jsonb, 'D', 'detail'),
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'mcq', 3, 'What does Priya identify as the biggest methodological weakness of their research?', 'Choose the correct letter, A, B or C.', 'listening/m03/part-3/full.mp3', '[{"label": "A", "text": "the small sample size"}, {"label": "B", "text": "the limited number of faculties surveyed"}, {"label": "C", "text": "the use of self-reporting for both key measures"}]'::jsonb, 'C', 'detail'),
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'mcq', 4, 'What did the students find most valuable in the Jensen and Park study?', NULL, 'listening/m03/part-3/full.mp3', '[{"label": "A", "text": "its framework for categorising social media behaviour"}, {"label": "B", "text": "its proposed measurement scale"}, {"label": "C", "text": "its findings on passive versus active use"}]'::jsonb, 'B', 'detail'),
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'mcq', 5, 'Which recommendation do both students agree should be removed from their report?', NULL, 'listening/m03/part-3/full.mp3', '[{"label": "A", "text": "digital literacy education in student induction"}, {"label": "B", "text": "optional wellbeing check-ins linked to academic support"}, {"label": "C", "text": "screen time caps for students"}]'::jsonb, 'C', 'detail'),
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'sentence_completion', 6, 'The students decide to include a diagram showing the passive-active use ___ from Jensen and Park in their presentation.', 'Complete the sentences below. Write NO MORE THAN TWO WORDS for each answer.', 'listening/m03/part-3/full.mp3', NULL, 'framework', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'sentence_completion', 7, 'The students agree that more time should have been allocated to ___ before the analysis phase began.', NULL, 'listening/m03/part-3/full.mp3', NULL, 'data cleaning', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'sentence_completion', 8, 'A key gap in the survey data was the failure to ask students about which specific ___ they were using.', NULL, 'listening/m03/part-3/full.mp3', NULL, 'platforms/platform type', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'sentence_completion', 9, 'Speaker A will be responsible for writing the ___ section of the written report.', NULL, 'listening/m03/part-3/full.mp3', NULL, 'discussion', 'completion'),
('a0000000-0000-4000-8000-000000000003', 'listening', 3, 'sentence_completion', 10, 'The deadline for submitting the written report is the ___ .', NULL, 'listening/m03/part-3/full.mp3', NULL, 'fourteenth/14th', 'completion');
