-- BandForge reading seed: The Machinery of Routine: Understanding How Habits Form and Change
-- mock_test_id = a0000000-0000-4000-8000-000000000003 part = 3

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'reading' AND part = 3
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'reading' AND part = 3;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 1, 3, 'Paragraph B', 'The Machinery of Routine: Understanding How Habits Form and Change

A    Habits constitute a significant proportion of human behaviour. A study conducted by Wood, Quinn, and Kashy, published in the Journal of Personality and Social Psychology in 2002, found that approximately forty-five percent of behaviours people performed each day were habitual — repeated in the same location and at roughly the same time each day, with little conscious deliberation. This finding challenged the prevailing assumption that most human action is the product of reasoned intention, and redirected scientific attention towards the automatic processes that govern so much of daily life. Understanding how habits form, persist, and can be altered has since become a central concern of behavioural psychology and, increasingly, of public health policy.

B    At the neurological level, habit formation involves a process of progressive automatisation within the brain''s basal ganglia — a set of subcortical structures associated with procedural learning and the regulation of voluntary movement. When a behaviour is performed repeatedly in a consistent context, the neural pathways associated with it become progressively strengthened, reducing the cognitive effort required to execute it. Researchers describe this process as chunking: the brain compresses a sequence of individual actions into a single, efficiently retrievable unit. Over time, the behaviour becomes triggered automatically by contextual cues — a particular time, place, or emotional state — with minimal involvement of the prefrontal cortex, the region associated with conscious decision-making.

C    The structure of habit has been described by psychologist Charles Duhigg, drawing on neuroscientific research, as a three-part loop consisting of a cue, a routine, and a reward. The cue is the trigger that initiates the habitual behaviour; the routine is the behaviour itself; and the reward is the outcome that reinforces the association between cue and routine, signalling to the brain that the loop is worth preserving. This framework has proven influential not only in academic psychology but in the design of commercial products and digital platforms, where understanding the habit loop has been used to engineer repeated engagement. The concept has been criticised, however, for oversimplifying the role of conscious motivation and for understating the degree to which context shapes whether rewards are perceived as such.

D    A persistent myth in popular culture holds that habits take precisely twenty-one days to form — a figure traced to observations made by plastic surgeon Maxwell Maltz in the 1960s regarding the time patients took to adjust to altered body images. Maltz''s figure was never the product of controlled empirical research, yet it circulated widely in self-help literature for decades. A more rigorous investigation was undertaken by Phillippa Lally and colleagues at University College London, whose 2010 study tracked participants attempting to establish new health behaviours over a twelve-week period. The study found that the time taken for a behaviour to reach automaticity varied considerably across individuals and behaviours, ranging from eighteen to two hundred and fifty-four days, with a median of sixty-six days. The variability underscores that habit formation is a deeply individual process, influenced by the complexity of the behaviour, the consistency of the context, and the motivation of the individual.

E    Habit change presents a distinct set of challenges from habit formation. Established habits are encoded in neural structures that are notably resistant to erasure; rather than being deleted, old habits are suppressed by competing neural pathways associated with new behaviours. This has an important practical implication: under conditions of stress, fatigue, or reduced cognitive control, the suppression of old habits weakens and previously established behaviours are liable to resurface. This phenomenon — sometimes described as habit relapse — is well documented in the addiction literature but applies equally to more mundane behavioural patterns. Effective habit change strategies therefore focus not merely on building new behaviours but on restructuring the environmental cues that trigger old ones.

F    Environment design has emerged as one of the most evidence-based approaches to supporting behaviour change. Rather than relying on willpower or conscious intention, this approach modifies the physical or social context in which behaviour occurs so that desired behaviours require less effort and undesired ones require more. Research by Brian Wansink at Cornell University demonstrated that simple changes to the presentation of food — such as using smaller plates or repositioning healthier options at eye level in cafeteria settings — produced measurable reductions in caloric intake without participants being consciously aware of the manipulation. While Wansink''s later work became subject to significant methodological scrutiny, the broader principle of environmental restructuring has been replicated across multiple independent research programmes.

G    The implications of habit science extend well beyond individual behaviour change. Policymakers and public health authorities have drawn on these findings to design intervention programmes targeting smoking cessation, physical activity, and dietary behaviour at population level. The concept of the nudge — a term popularised by Thaler and Sunstein in their 2008 book Nudge — represents an application of habit and behavioural science to the architecture of public choice, seeking to make desirable behaviours the path of least resistance without removing individual freedom. Critics of this approach argue that nudge-based interventions address symptoms rather than the structural determinants of unhealthy behaviour, and that their effects are modest and frequently temporary. The debate reflects a wider tension in behavioural science between individual-level and systems-level explanations of human conduct.', '[{"label": "i", "text": "The neurological mechanism by which repeated behaviours become automatic"}, {"label": "ii", "text": "Why individuals revert to old behaviours under pressure"}, {"label": "iii", "text": "The commercial exploitation of psychological research into motivation"}, {"label": "iv", "text": "A three-stage model of habitual behaviour and its limitations"}, {"label": "v", "text": "Evidence that habit formation timelines vary widely between individuals"}, {"label": "vi", "text": "The role of social environment in reinforcing habitual behaviour patterns"}, {"label": "vii", "text": "How stress and fatigue affect the brain''s capacity for learning new skills"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 2, 3, 'Paragraph C', NULL, '[{"label": "i", "text": "The neurological mechanism by which repeated behaviours become automatic"}, {"label": "ii", "text": "Why individuals revert to old behaviours under pressure"}, {"label": "iii", "text": "The commercial exploitation of psychological research into motivation"}, {"label": "iv", "text": "A three-stage model of habitual behaviour and its limitations"}, {"label": "v", "text": "Evidence that habit formation timelines vary widely between individuals"}, {"label": "vi", "text": "The role of social environment in reinforcing habitual behaviour patterns"}, {"label": "vii", "text": "How stress and fatigue affect the brain''s capacity for learning new skills"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 3, 3, 'Paragraph D', NULL, '[{"label": "i", "text": "The neurological mechanism by which repeated behaviours become automatic"}, {"label": "ii", "text": "Why individuals revert to old behaviours under pressure"}, {"label": "iii", "text": "The commercial exploitation of psychological research into motivation"}, {"label": "iv", "text": "A three-stage model of habitual behaviour and its limitations"}, {"label": "v", "text": "Evidence that habit formation timelines vary widely between individuals"}, {"label": "vi", "text": "The role of social environment in reinforcing habitual behaviour patterns"}, {"label": "vii", "text": "How stress and fatigue affect the brain''s capacity for learning new skills"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 4, 3, 'Paragraph E', NULL, '[{"label": "i", "text": "The neurological mechanism by which repeated behaviours become automatic"}, {"label": "ii", "text": "Why individuals revert to old behaviours under pressure"}, {"label": "iii", "text": "The commercial exploitation of psychological research into motivation"}, {"label": "iv", "text": "A three-stage model of habitual behaviour and its limitations"}, {"label": "v", "text": "Evidence that habit formation timelines vary widely between individuals"}, {"label": "vi", "text": "The role of social environment in reinforcing habitual behaviour patterns"}, {"label": "vii", "text": "How stress and fatigue affect the brain''s capacity for learning new skills"}]'::jsonb, 'ii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_features', 5, 3, 'Wood, Quinn, and Kashy (2002)', NULL, '[{"label": "A", "text": "Found that close to half of daily human behaviours are performed automatically without conscious thought"}, {"label": "B", "text": "Described how the brain organises repeated actions into efficiently retrievable sequences"}, {"label": "C", "text": "Proposed a widely repeated but empirically unsupported timeline for habit formation"}, {"label": "D", "text": "Demonstrated that altering food presentation could change eating behaviour without conscious awareness"}, {"label": "E", "text": "Established that the time required to form a habit ranges from under three weeks to over eight months"}, {"label": "F", "text": "Applied behavioural science principles to the design of public policy choices"}, {"label": "G", "text": "Argued that habit change requires restructuring the environment rather than relying on motivation alone"}]'::jsonb, 'A', 'matching_features'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_features', 6, 3, 'Maxwell Maltz', NULL, '[{"label": "A", "text": "Found that close to half of daily human behaviours are performed automatically without conscious thought"}, {"label": "B", "text": "Described how the brain organises repeated actions into efficiently retrievable sequences"}, {"label": "C", "text": "Proposed a widely repeated but empirically unsupported timeline for habit formation"}, {"label": "D", "text": "Demonstrated that altering food presentation could change eating behaviour without conscious awareness"}, {"label": "E", "text": "Established that the time required to form a habit ranges from under three weeks to over eight months"}, {"label": "F", "text": "Applied behavioural science principles to the design of public policy choices"}, {"label": "G", "text": "Argued that habit change requires restructuring the environment rather than relying on motivation alone"}]'::jsonb, 'C', 'matching_features'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_features', 7, 3, 'Phillippa Lally et al. (2010)', NULL, '[{"label": "A", "text": "Found that close to half of daily human behaviours are performed automatically without conscious thought"}, {"label": "B", "text": "Described how the brain organises repeated actions into efficiently retrievable sequences"}, {"label": "C", "text": "Proposed a widely repeated but empirically unsupported timeline for habit formation"}, {"label": "D", "text": "Demonstrated that altering food presentation could change eating behaviour without conscious awareness"}, {"label": "E", "text": "Established that the time required to form a habit ranges from under three weeks to over eight months"}, {"label": "F", "text": "Applied behavioural science principles to the design of public policy choices"}, {"label": "G", "text": "Argued that habit change requires restructuring the environment rather than relying on motivation alone"}]'::jsonb, 'E', 'matching_features'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_features', 8, 3, 'Brian Wansink', NULL, '[{"label": "A", "text": "Found that close to half of daily human behaviours are performed automatically without conscious thought"}, {"label": "B", "text": "Described how the brain organises repeated actions into efficiently retrievable sequences"}, {"label": "C", "text": "Proposed a widely repeated but empirically unsupported timeline for habit formation"}, {"label": "D", "text": "Demonstrated that altering food presentation could change eating behaviour without conscious awareness"}, {"label": "E", "text": "Established that the time required to form a habit ranges from under three weeks to over eight months"}, {"label": "F", "text": "Applied behavioural science principles to the design of public policy choices"}, {"label": "G", "text": "Argued that habit change requires restructuring the environment rather than relying on motivation alone"}]'::jsonb, 'D', 'matching_features'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'sentence_completion', 9, 3, 'Neuroscientists use the term ______________ to describe the process by which the brain compresses a series of actions into a single retrievable unit.', NULL, NULL, 'chunking', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'sentence_completion', 10, 3, 'According to Duhigg''s framework, the element of the habit loop that reinforces the connection between a trigger and a behaviour is called the ______________.', NULL, NULL, 'reward', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'sentence_completion', 11, 3, 'The Lally study found that the median number of days required for a new behaviour to reach ______________ was sixty-six.', NULL, NULL, 'automaticity', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'sentence_completion', 12, 3, 'The tendency for previously established behaviours to return when cognitive control is reduced is referred to in the passage as ______________.', NULL, NULL, 'habit relapse', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'sentence_completion', 13, 3, 'The term ______________ was introduced to describe the application of behavioural science to the design of public choice environments.', NULL, NULL, 'nudge', 'sentence_completion');
