-- BandForge reading seed: The Sentinels of the Shore: Kelp Forest Ecosystems and Their Uncertain Future
-- mock_test_id = a0000000-0000-4000-8000-000000000003 part = 2

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'reading' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000003' AND module = 'reading' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 1, 2, 'The structural complexity of kelp forests makes them comparable in biodiversity to the most species-rich marine environments on Earth.', 'The Sentinels of the Shore: Kelp Forest Ecosystems and Their Uncertain Future

A    Among the most productive ecosystems on Earth, kelp forests occupy a narrow band of cold, nutrient-rich coastal waters extending along the western margins of every major continent. Dominated by giant kelp — Macrocystis pyrifera — which can grow at rates of up to sixty centimetres per day and reach heights of forty-five metres, these underwater forests create a three-dimensional habitat of extraordinary complexity. Like their terrestrial counterparts, kelp forests are structured in distinct vertical layers: a canopy formed by the uppermost fronds, a mid-water column inhabited by fish and invertebrates, and a seafloor zone where light is scarce and conditions favour specialist organisms. This architectural richness supports an estimated eight hundred species in well-developed kelp forest systems, making them among the most biodiverse marine environments outside tropical reef zones.

B    The ecological functioning of kelp forests is governed to a remarkable degree by the relationships between a small number of keystone species. The sea otter (Enhydra lutris) occupies a position of disproportionate influence within North Pacific kelp ecosystems. Otters prey heavily on sea urchins, which are themselves voracious consumers of kelp. In the absence of otters, urchin populations expand unchecked and can reduce a thriving kelp forest to a barren, urchin-dominated seabed — a phenomenon ecologists have termed an urchin barren. The importance of this predator-prey dynamic was formally demonstrated by the ecologist Robert Paine, whose field experiments in the 1960s established the concept of the keystone species, a term now fundamental to ecological science. Paine''s work showed that the removal of a single predator could precipitate cascading changes throughout an entire ecosystem.

C    The historical record of sea otter populations illustrates the consequences of disrupting this balance at scale. Commercial hunting during the eighteenth and nineteenth centuries reduced global sea otter numbers from an estimated population of between 150,000 and 300,000 individuals to fewer than 2,000 by the early twentieth century. Across much of the North Pacific, the collapse of otter populations was followed by explosive growth in sea urchin numbers and the subsequent destruction of kelp forest habitat. Partial recovery of otter populations following international protection agreements in the early twentieth century led, in many areas, to measurable kelp forest regeneration — a natural experiment that provided some of the most compelling evidence for the keystone species concept in any marine environment.

D    Climate change has introduced a new and more complex set of pressures on kelp forest systems globally. Rising sea temperatures are of particular concern, as giant kelp is physiologically intolerant of sustained warmth, with growth rates declining sharply when water temperatures exceed eighteen degrees Celsius. Marine heatwaves — episodes of anomalously warm surface water lasting weeks or months — have become more frequent and intense over recent decades. Off the coast of Tasmania, a marine heatwave in 2011 caused the loss of approximately ninety-five percent of the kelp canopy across a stretch of coastline that had previously supported one of the southern hemisphere''s most extensive kelp forest systems. Recovery has been negligible in the years since, partly because warmer baseline temperatures have prevented re-establishment of the canopy even in the absence of acute heat events.

E    The decline of kelp forests carries significant consequences for the communities and industries that depend on them. Commercial fisheries for species including rock lobster, abalone, and a range of fin fish are closely tied to the productivity of kelp ecosystems, which serve as both nursery habitat and feeding grounds for economically important species. In California, where kelp forest management has been a policy concern since the mid-twentieth century, the abalone fishery collapsed entirely in the late 1990s following a combination of overharvesting and kelp decline driven by urchin population explosions. The cultural significance of kelp forests to Indigenous coastal communities, particularly along the Pacific coast of North America, adds a further dimension to the cost of their degradation that economic valuations alone cannot capture.

F    Restoration efforts have gained momentum in recent years, drawing on both ecological principles and emerging biotechnology. The most widely implemented approach involves manual or mechanical removal of urchins from targeted reef areas, allowing kelp recruitment to resume in the absence of herbivory pressure. In California, volunteer dive programmes have removed millions of purple sea urchins from priority sites since 2018, with measurable recovery of kelp canopy observed in several locations. More experimental interventions include the selective breeding of thermally tolerant kelp varieties, an approach pioneered by researchers at the University of California, Santa Barbara, who have identified genetic variants capable of sustaining growth at temperatures that would arrest development in wild populations. The long-term viability of such interventions at ecologically meaningful scales, however, remains to be established.

G    The future of kelp forest ecosystems is inseparable from the broader trajectory of ocean warming and the policy responses it demands. Scientists working in this field are broadly agreed that without significant reductions in greenhouse gas emissions, the thermal envelope within which giant kelp can thrive will contract progressively, eliminating forests from regions where they have persisted for millennia. Some researchers have proposed the deliberate translocation of cold-water adapted kelp populations to higher latitudes as a long-term adaptive strategy, though this remains contested on ecological grounds. What is not contested is the urgency of the situation: the ecosystems that Robert Paine spent his career studying are disappearing faster than the science of their restoration can advance.', '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 2, 2, 'Robert Paine''s research in the 1960s was the first scientific work to examine predator-prey relationships in marine environments.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NOT GIVEN', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 3, 2, 'The recovery of sea otter populations after legal protection provided strong evidence for the importance of keystone species.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 4, 2, 'Rising ocean temperatures pose a greater long-term threat to kelp forests than sea urchin population explosions.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NOT GIVEN', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'tfng', 5, 2, 'The selective breeding of thermally tolerant kelp varieties has been conclusively shown to work at the scale required for ecological restoration.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 6, 2, 'Paragraph B', NULL, '[{"label": "i", "text": "How the hunting of a single species triggered the collapse of an entire ecosystem"}, {"label": "ii", "text": "The disproportionate influence of predators on kelp ecosystem stability"}, {"label": "iii", "text": "Economic and cultural losses resulting from kelp forest degradation"}, {"label": "iv", "text": "The challenge of restoring kelp forests in a warming ocean"}, {"label": "v", "text": "Why cold water is essential to the survival of deep-sea marine species"}, {"label": "vi", "text": "The impact of warming seas and extreme weather events on kelp systems"}, {"label": "vii", "text": "Government policy responses to the decline of commercial kelp fisheries"}]'::jsonb, 'ii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 7, 2, 'Paragraph C', NULL, '[{"label": "i", "text": "How the hunting of a single species triggered the collapse of an entire ecosystem"}, {"label": "ii", "text": "The disproportionate influence of predators on kelp ecosystem stability"}, {"label": "iii", "text": "Economic and cultural losses resulting from kelp forest degradation"}, {"label": "iv", "text": "The challenge of restoring kelp forests in a warming ocean"}, {"label": "v", "text": "Why cold water is essential to the survival of deep-sea marine species"}, {"label": "vi", "text": "The impact of warming seas and extreme weather events on kelp systems"}, {"label": "vii", "text": "Government policy responses to the decline of commercial kelp fisheries"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 8, 2, 'Paragraph D', NULL, '[{"label": "i", "text": "How the hunting of a single species triggered the collapse of an entire ecosystem"}, {"label": "ii", "text": "The disproportionate influence of predators on kelp ecosystem stability"}, {"label": "iii", "text": "Economic and cultural losses resulting from kelp forest degradation"}, {"label": "iv", "text": "The challenge of restoring kelp forests in a warming ocean"}, {"label": "v", "text": "Why cold water is essential to the survival of deep-sea marine species"}, {"label": "vi", "text": "The impact of warming seas and extreme weather events on kelp systems"}, {"label": "vii", "text": "Government policy responses to the decline of commercial kelp fisheries"}]'::jsonb, 'vi', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'matching_headings', 9, 2, 'Paragraph E', NULL, '[{"label": "i", "text": "How the hunting of a single species triggered the collapse of an entire ecosystem"}, {"label": "ii", "text": "The disproportionate influence of predators on kelp ecosystem stability"}, {"label": "iii", "text": "Economic and cultural losses resulting from kelp forest degradation"}, {"label": "iv", "text": "The challenge of restoring kelp forests in a warming ocean"}, {"label": "v", "text": "Why cold water is essential to the survival of deep-sea marine species"}, {"label": "vi", "text": "The impact of warming seas and extreme weather events on kelp systems"}, {"label": "vii", "text": "Government policy responses to the decline of commercial kelp fisheries"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'mcq', 10, 2, 'According to the passage, what is the significance of the sea otter within North Pacific kelp ecosystems?', NULL, '[{"label": "A", "text": "It directly consumes kelp fronds, keeping canopy growth within sustainable limits."}, {"label": "B", "text": "It controls sea urchin populations, preventing the destruction of kelp habitat."}, {"label": "C", "text": "It competes with commercial fisheries for the same prey species."}, {"label": "D", "text": "It was identified by Robert Paine as the primary driver of kelp forest biodiversity."}]'::jsonb, 'B', 'mcq'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'mcq', 11, 2, 'What does the writer suggest about the kelp forests off the coast of Tasmania?', NULL, '[{"label": "A", "text": "They have made a substantial recovery since the 2011 marine heatwave."}, {"label": "B", "text": "They were already in decline before the 2011 heatwave due to urchin pressure."}, {"label": "C", "text": "They have struggled to recover because warmer baseline temperatures persist."}, {"label": "D", "text": "They represent the largest kelp forest system in the southern hemisphere."}]'::jsonb, 'C', 'mcq'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'mcq', 12, 2, 'According to the passage, what caused the collapse of the abalone fishery in California in the late 1990s?', NULL, '[{"label": "A", "text": "The reintroduction of sea otters, which competed directly with abalone for food."}, {"label": "B", "text": "A combination of excessive fishing and kelp decline linked to urchin population growth."}, {"label": "C", "text": "A marine heatwave that destroyed the kelp canopy across the California coastline."}, {"label": "D", "text": "The introduction of an invasive urchin species that displaced native abalone populations."}]'::jsonb, 'B', 'mcq'),
('a0000000-0000-4000-8000-000000000003', 'reading', 'mcq', 13, 2, 'What point does the writer make about the selective breeding programme at the University of California, Santa Barbara?', NULL, '[{"label": "A", "text": "It has already restored kelp forests across several high-priority sites in California."}, {"label": "B", "text": "It has produced kelp varieties that can grow in warmer water but its large-scale impact is unproven."}, {"label": "C", "text": "It is the most cost-effective restoration approach currently available to marine ecologists."}, {"label": "D", "text": "It was developed in direct response to the Tasmanian kelp collapse of 2011."}]'::jsonb, 'B', 'mcq');
