-- BandForge reading seed: Automation, AI & the Future of Labour
-- mock_test_id = a0000000-0000-4000-8000-000000000004 part = 1

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'reading' AND part = 1
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'reading' AND part = 1;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 1, 1, 'Historical predictions of mass unemployment caused by technology have generally proven accurate.', 'Automation, AI & the Future of Labour

A For over two centuries, technological change has provoked anxiety about the displacement of human labour. The power loom, the assembly line, and the personal computer each triggered predictions of mass unemployment that, in the long run, failed to materialise at the scale forecast. Artificial intelligence, however, is frequently described as categorically different. Unlike earlier waves of automation, which primarily replaced physical, repetitive tasks, AI systems increasingly perform cognitive functions — drafting text, analysing data, diagnosing medical images — that were long considered the exclusive domain of skilled professionals.

B Economists broadly agree that automation destroys some jobs while creating others, but they disagree sharply on the net effect and the timeline. A widely cited 2023 study estimated that generative AI tools could affect tasks making up 60 to 70 percent of employees'' working hours across advanced economies, though the researchers were careful to distinguish between tasks being augmented and jobs being eliminated. Augmentation — where a technology handles part of a role, freeing the worker for higher-value activity — has historically been the more common outcome, but the speed of the current transition leaves less time for workers and institutions to adjust.

C The distributional consequences are a particular source of concern. Previous automation waves tended to hollow out middle-skill jobs, such as manufacturing and clerical work, while leaving low-skill service roles and high-skill professional roles relatively intact — a pattern economists call job polarisation. AI-driven automation appears to follow a different distribution, placing downward pressure on certain high-skill, high-wage occupations, including paralegal work, financial analysis, and even some aspects of software development, while many manual service jobs, from plumbing to elder care, remain comparatively insulated because they require physical dexterity and situational judgement that current systems cannot replicate.

D Governments have responded with a range of policy instruments, though none has yet proven definitive. Universal basic income pilots in Finland, Kenya, and parts of the United States have produced mixed results: recipients reported improved wellbeing and modestly increased entrepreneurial activity, but the pilots were too small and short-lived to answer the central question of whether such schemes are fiscally sustainable at national scale. Retraining programmes have fared unevenly; evaluations suggest that short courses focused on narrow technical skills produce better employment outcomes than broader "upskilling" initiatives, though the latter are more popular with policymakers because they appear to address the problem more comprehensively.

E A less-discussed dimension of the debate concerns organisational structure rather than individual jobs. As AI systems take on tasks previously requiring several layers of human review, some firms have begun flattening their management hierarchies, reducing the number of middle managers whose primary function was coordination and quality control. Proponents argue this increases efficiency and speeds decision-making; critics counter that it removes the informal mentorship and judgement-transfer that middle management historically provided to junior staff, with consequences that may only become visible over a longer time horizon.

F What most researchers agree on is that the outcome is not technologically predetermined. The same automation technology can be deployed to replace workers outright or to augment their capabilities, and the choice between these paths is shaped by corporate incentives, labour market institutions, and public policy rather than by the technology itself. This suggests that the anxious framing of "humans versus machines" may obscure the more consequential question: which institutions and policies will determine how the gains from automation are distributed.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 2, 1, 'AI differs from earlier automation because it can perform cognitive as well as physical tasks.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 3, 1, 'The 2023 study concluded that most affected jobs would be entirely eliminated.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 4, 1, 'Earlier waves of automation mainly disadvantaged middle-skill occupations.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 5, 1, 'All high-skill professions are equally vulnerable to AI-driven automation.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 6, 1, 'Universal basic income pilots have conclusively proven the approach is not fiscally viable.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NOT GIVEN', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_features', 7, 1, 'Narrow, technically focused retraining courses', NULL, '[{"label": "A", "text": "are favoured by policymakers despite weaker outcomes."}, {"label": "B", "text": "depends on institutional and policy choices, not the technology itself."}, {"label": "C", "text": "tend to produce better employment outcomes than broader alternatives."}, {"label": "D", "text": "may remove informal mentorship for junior employees."}, {"label": "E", "text": "have been rejected by most national governments."}, {"label": "F", "text": "require physical dexterity that AI cannot replicate."}]'::jsonb, 'C', 'matching_features'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_features', 8, 1, 'Broad upskilling programmes', NULL, '[{"label": "A", "text": "are favoured by policymakers despite weaker outcomes."}, {"label": "B", "text": "depends on institutional and policy choices, not the technology itself."}, {"label": "C", "text": "tend to produce better employment outcomes than broader alternatives."}, {"label": "D", "text": "may remove informal mentorship for junior employees."}, {"label": "E", "text": "have been rejected by most national governments."}, {"label": "F", "text": "require physical dexterity that AI cannot replicate."}]'::jsonb, 'A', 'matching_features'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_features', 9, 1, 'Flattened management hierarchies', NULL, '[{"label": "A", "text": "are favoured by policymakers despite weaker outcomes."}, {"label": "B", "text": "depends on institutional and policy choices, not the technology itself."}, {"label": "C", "text": "tend to produce better employment outcomes than broader alternatives."}, {"label": "D", "text": "may remove informal mentorship for junior employees."}, {"label": "E", "text": "have been rejected by most national governments."}, {"label": "F", "text": "require physical dexterity that AI cannot replicate."}]'::jsonb, 'D', 'matching_features'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_features', 10, 1, 'The overall outcome of automation for workers', NULL, '[{"label": "A", "text": "are favoured by policymakers despite weaker outcomes."}, {"label": "B", "text": "depends on institutional and policy choices, not the technology itself."}, {"label": "C", "text": "tend to produce better employment outcomes than broader alternatives."}, {"label": "D", "text": "may remove informal mentorship for junior employees."}, {"label": "E", "text": "have been rejected by most national governments."}, {"label": "F", "text": "require physical dexterity that AI cannot replicate."}]'::jsonb, 'B', 'matching_features'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'sentence_completion', 11, 1, 'What term do economists use to describe the hollowing-out of middle-skill jobs? ______________', NULL, NULL, 'job polarisation/job polarization', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'sentence_completion', 12, 1, 'According to the passage, what capability allows manual service jobs to remain relatively insulated from automation? ______________', NULL, NULL, 'physical dexterity/situational judgement/situational judgment', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'sentence_completion', 13, 1, 'What have some firms started reducing as AI takes on more review tasks? ______________', NULL, NULL, 'middle managers/middle management', 'sentence_completion');
