-- BandForge reading seed: Data Privacy & Digital Rights
-- mock_test_id = a0000000-0000-4000-8000-000000000004 part = 3

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'reading' AND part = 3
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'reading' AND part = 3;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 27, 3, 'A description of an alternative model that does not rely on individual consent', 'Data Privacy & Digital Rights
A The rapid expansion of data collection by governments and corporations has forced legal systems worldwide to confront a question they were never designed to answer: who owns information about a person, and what rights does that person retain over its use? The European Union''s General Data Protection Regulation (GDPR), enacted in 2018, represented the most comprehensive attempt yet to answer this question, establishing principles such as data minimisation, purpose limitation, and the "right to be forgotten" that have since influenced legislation well beyond Europe''s borders.
B Critics of GDPR-style regulation argue that compliance costs disproportionately burden smaller companies, entrenching the market dominance of large technology firms with the legal and technical resources to navigate complex requirements. A 2019 study found that after GDPR''s implementation, venture capital investment in European technology startups declined relative to comparable American firms, a finding regulation''s defenders dispute, arguing the causal link is weaker than critics claim and that other factors, including broader market conditions, better explain the divergence.
C A separate but related debate concerns the concept of consent itself. Data protection frameworks typically require that individuals consent to data collection, yet critics note that this model assumes a degree of understanding and bargaining power that rarely exists in practice. Terms-of-service agreements routinely run to thousands of words, and studies have repeatedly found that the overwhelming majority of users do not read them before clicking "accept." Some legal scholars argue that consent-based frameworks have therefore become largely symbolic, providing legal cover for data practices that few users meaningfully understand or would endorse if the implications were made clear.
D An alternative approach, gaining traction particularly in academic and some regulatory circles, treats certain categories of data — biometric information, health records, and location history in particular — as warranting protection regardless of consent, on the grounds that individuals cannot adequately assess long-term risks at the point of collection. This model shifts responsibility from the individual, who is expected to police the flow of their own data, toward the institution collecting it, which bears an obligation to justify collection and minimise harm independent of whether formal consent was obtained.
E Facial recognition technology has become a focal point for these debates because it exposes the limits of individual consent as a regulatory mechanism. A person walking through a public space captured by a facial recognition system has typically not consented to anything, yet their biometric data may be collected, stored, and matched against databases regardless. Several jurisdictions, including some American cities and Chinese municipalities operating under different rationales, have introduced restrictions on facial recognition use by police and private companies, though enforcement and scope vary considerably, and technology continues to outpace the legislative processes meant to govern it.
F Looking ahead, legal scholars increasingly argue that data protection law must shift from a framework centred on individual transactions and consent toward one centred on systemic risk and institutional accountability. This would mean regulating not merely how data is collected, but how it is aggregated, combined with other datasets, and used to make consequential decisions about individuals — decisions in areas such as insurance pricing, credit eligibility, and employment screening, where the cumulative effect of many small, individually consented-to data points can produce outcomes no single person anticipated or agreed to.
G Whatever direction reform takes, most observers agree that the pace of technological change means data protection law will remain in a state of continual revision rather than settled resolution, with each new technology — from facial recognition to increasingly sophisticated predictive analytics — reopening questions that earlier legislation was not designed to answer.', NULL, 'D', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 28, 3, 'Mention of a disputed study on the economic effects of data regulation', NULL, NULL, 'B', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 29, 3, 'A general prediction about the future trajectory of data protection law', NULL, NULL, 'G', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 30, 3, 'An example illustrating the practical limits of consent-based frameworks', NULL, NULL, 'E', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 31, 3, 'A description of GDPR''s core founding principles', NULL, NULL, 'A', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 32, 3, 'Terms-of-service agreements that are rarely read in full', NULL, NULL, 'C', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 33, 3, 'Data categories proposed for special protection regardless of consent', NULL, NULL, 'D', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 34, 3, 'Facial recognition data collected without any consent process', NULL, NULL, 'E', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 35, 3, 'Compliance costs said to favour large technology firms', NULL, NULL, 'B', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 36, 3, 'Aggregation of individually consented-to data producing unanticipated outcomes', NULL, NULL, 'F', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'sentence_completion', 37, 3, 'What right, established under GDPR, allows individuals to request the erasure of their data? ______________', NULL, NULL, 'right to be forgotten/the right to be forgotten', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'sentence_completion', 38, 3, 'What term describes the situation where consent frameworks provide legal cover without genuine understanding? ______________', NULL, NULL, 'symbolic/largely symbolic', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'sentence_completion', 39, 3, 'According to the passage, what should institutions bear responsibility for under the alternative data-protection model? ______________', NULL, NULL, 'minimise harm/minimize harm/justify collection', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'sentence_completion', 40, 3, 'What kind of decisions does the passage cite as examples of the cumulative effects of aggregated data (insurance pricing, credit eligibility, and what else)? ______________', NULL, NULL, 'employment screening', 'sentence_completion');
