-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000004

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'listening' AND part = 1
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'listening' AND part = 1;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 1, 'Surname', 'Complete the form below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.

@@form_title@@UNIVERSITY ADMISSIONS — APPLICANT ENQUIRY FORM', 'listening/m04/part-1/full.mp3', NULL, 'Nandakumar', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 2, 'Mobile number', NULL, 'listening/m04/part-1/full.mp3', NULL, '09899 903321/09899903321', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 3, 'Most recent qualification', NULL, 'listening/m04/part-1/full.mp3', NULL, 'Statistics', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 4, 'Previous institution', NULL, 'listening/m04/part-1/full.mp3', NULL, 'Ashwood University', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 5, 'Preferred intake', NULL, 'listening/m04/part-1/full.mp3', NULL, 'September', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 6, 'Outstanding document', NULL, 'listening/m04/part-1/full.mp3', NULL, 'reference letter', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 7, 'Application fee', NULL, 'listening/m04/part-1/full.mp3', NULL, '120/£120', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 8, 'Coordinator appointment day', NULL, 'listening/m04/part-1/full.mp3', NULL, 'Thursday', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 9, 'Applicant reference', NULL, 'listening/m04/part-1/full.mp3', NULL, 'AR4472', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 1, 'form_completion', 10, 'Preferred campus', NULL, 'listening/m04/part-1/full.mp3', NULL, 'Riverside', 'completion');
