-- BandForge reading seed: Cognitive Bias & Decision-Making
-- mock_test_id = a0000000-0000-4000-8000-000000000004 part = 2

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'reading' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'reading' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 14, 2, 'Cognitive biases occur in random, unpredictable patterns.', 'Cognitive Bias & Decision-Making
A Human beings like to think of themselves as rational decision-makers, yet decades of research in behavioural psychology suggest otherwise. Cognitive biases — systematic patterns of deviation from rational judgement — influence choices ranging from what people buy to how doctors diagnose illness and how judges set bail. Far from being random errors, these biases follow predictable patterns, which is precisely what makes them useful to study and, in some contexts, possible to correct for.
B One of the most extensively studied biases is anchoring, first documented by psychologists Amos Tversky and Daniel Kahneman in the 1970s. Anchoring describes the tendency for an initial piece of information — even an arbitrary one — to disproportionately influence subsequent judgements. In a classic experiment, participants spun a wheel rigged to land on either a low or high number, then were asked to estimate the percentage of African countries in the United Nations. Those who saw the higher number gave substantially higher estimates, despite the number on the wheel having no logical connection to the question. Anchoring is now understood to affect real-world decisions such as salary negotiations and property pricing, where an initial figure — however arbitrary — sets a reference point that subsequent discussion rarely departs far from.
C Confirmation bias, the tendency to seek out and favour information that supports existing beliefs while discounting contradictory evidence, is perhaps the most consequential bias in terms of its societal effects. It shapes how people interpret news, evaluate scientific claims, and form political opinions. Critically, confirmation bias does not require dishonesty or low intelligence; highly educated individuals are just as susceptible, and in some studies more susceptible, because they are more skilled at constructing plausible-sounding justifications for conclusions they already favour — a phenomenon researchers term "motivated reasoning."
D A third bias, loss aversion, describes the observation that the psychological pain of losing something is felt roughly twice as intensely as the pleasure of gaining an equivalent amount. This asymmetry explains a wide range of seemingly irrational behaviour, from investors holding onto losing stocks far longer than rational analysis would recommend, to consumers being disproportionately swayed by "limited time only" framing that emphasises potential loss over potential gain. Loss aversion is now a foundational concept in behavioural economics and has directly informed the design of retirement savings schemes, which increasingly use default enrolment — exploiting the related tendency toward inertia — rather than requiring an active opt-in decision.
E Recognising the existence of these biases has proven far easier than correcting for them. Simply informing people about a bias rarely reduces its influence on their subsequent judgements; in some studies, awareness of a bias even produced a false sense of immunity, leading participants to underestimate their own susceptibility while remaining alert to it in others — an effect researchers have labelled the "bias blind spot." More effective interventions tend to involve structural changes to the decision-making environment itself, such as requiring decision-makers to consider explicitly opposing evidence, or redesigning forms and defaults so that the "easy" choice aligns with better outcomes, rather than relying on individuals to overcome their own cognitive wiring through willpower alone.
F This has significant implications for fields ranging from medicine to public policy. Hospitals have begun implementing structured checklists partly to counteract anchoring in diagnosis, where an initial impression can unduly influence subsequent tests and interpretations. Policymakers, meanwhile, increasingly draw on "choice architecture" — restructuring how options are presented — as a lower-cost, higher-impact alternative to public information campaigns, which research suggests are comparatively ineffective at changing entrenched behaviour.', '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 15, 2, 'The wheel-spinning experiment showed that arbitrary numbers can influence unrelated estimates.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 16, 2, 'Anchoring effects are limited to laboratory settings and do not occur in real-world negotiations.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 17, 2, 'Highly educated individuals are generally less susceptible to confirmation bias than others.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 18, 2, 'Loss aversion means losses are felt more intensely than equivalent gains are enjoyed.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'tfng', 19, 2, 'Retirement scheme defaults were redesigned in direct response to loss aversion research.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 20, 2, 'An example of a bias being exploited by policymakers to promote better outcomes', NULL, NULL, 'F', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 21, 2, 'A description of a bias affecting how people process politically charged information', NULL, NULL, 'C', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 22, 2, 'An explanation of why simply teaching people about bias often fails to reduce it', NULL, NULL, 'E', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_information', 23, 2, 'A specific example of biased behaviour among financial investors', NULL, NULL, 'D', 'matching_information'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_features', 24, 2, 'Interventions aimed purely at raising ___ of cognitive bias have proven largely ineffective', NULL, '[{"label": "A", "text": "awareness"}, {"label": "B", "text": "decision-making environment"}, {"label": "C", "text": "bias blind spot"}, {"label": "D", "text": "salary"}, {"label": "E", "text": "false confidence"}, {"label": "F", "text": "anchoring effect"}, {"label": "G", "text": "motivated reasoning"}, {"label": "H", "text": "checklist"}, {"label": "I", "text": "immunity"}]'::jsonb, 'A', 'matching_features'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_features', 25, 2, 'sometimes even producing a ___, whereby people believe themselves less vulnerable than others', NULL, '[{"label": "A", "text": "awareness"}, {"label": "B", "text": "decision-making environment"}, {"label": "C", "text": "bias blind spot"}, {"label": "D", "text": "salary"}, {"label": "E", "text": "false confidence"}, {"label": "F", "text": "anchoring effect"}, {"label": "G", "text": "motivated reasoning"}, {"label": "H", "text": "checklist"}, {"label": "I", "text": "immunity"}]'::jsonb, 'C', 'matching_features'),
('a0000000-0000-4000-8000-000000000004', 'reading', 'matching_features', 26, 2, 'More effective approaches tend to focus on redesigning the ___ itself', NULL, '[{"label": "A", "text": "awareness"}, {"label": "B", "text": "decision-making environment"}, {"label": "C", "text": "bias blind spot"}, {"label": "D", "text": "salary"}, {"label": "E", "text": "false confidence"}, {"label": "F", "text": "anchoring effect"}, {"label": "G", "text": "motivated reasoning"}, {"label": "H", "text": "checklist"}, {"label": "I", "text": "immunity"}]'::jsonb, 'B', 'matching_features');
