-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000004

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'listening' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'listening' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'mcq', 1, 'How many themed zones does the expo have this year?', 'Choose the correct letter, A, B or C.', 'listening/m04/part-2/full.mp3', '[{"label": "A", "text": "three"}, {"label": "B", "text": "five"}, {"label": "C", "text": "four"}]'::jsonb, 'C', 'detail'),
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'mcq', 2, 'What time does the Mobility zone open?', NULL, 'listening/m04/part-2/full.mp3', '[{"label": "A", "text": "nine"}, {"label": "B", "text": "ten"}, {"label": "C", "text": "eleven"}]'::jsonb, 'B', 'detail'),
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'mcq', 3, 'How was the air quality display funded?', NULL, 'listening/m04/part-2/full.mp3', '[{"label": "A", "text": "an exhibitor"}, {"label": "B", "text": "a public grant"}, {"label": "C", "text": "ticket sales"}]'::jsonb, 'B', 'detail'),
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'mcq', 4, 'Where can visitors sign up for the newsletter?', NULL, 'listening/m04/part-2/full.mp3', '[{"label": "A", "text": "the info desk"}, {"label": "B", "text": "Zone 1"}, {"label": "C", "text": "by the exit"}]'::jsonb, 'C', 'detail'),
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'sentence_completion', 5, 'The air quality readings update every ___ .', 'Complete the sentences below. Write NO MORE THAN TWO WORDS for each answer.', 'listening/m04/part-2/full.mp3', NULL, 'minute', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'sentence_completion', 6, 'The smart lighting pilot cut energy use by ___ per cent.', NULL, 'listening/m04/part-2/full.mp3', NULL, '40/forty', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'sentence_completion', 7, 'Workshop seats can be reserved at the ___ desk.', NULL, 'listening/m04/part-2/full.mp3', NULL, 'information', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'sentence_completion', 8, 'Parking is free for the first ___ .', NULL, 'listening/m04/part-2/full.mp3', NULL, 'hour', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'sentence_completion', 9, 'The prize draw winner receives a ___ to next year''s expo.', NULL, 'listening/m04/part-2/full.mp3', NULL, 'pass/free pass', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 2, 'sentence_completion', 10, 'Wristbands give access to every zone, including the afternoon ___ workshop.', NULL, 'listening/m04/part-2/full.mp3', NULL, 'sensor networks', 'completion');
