-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000004

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'listening' AND part = 3
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'listening' AND part = 3;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'mcq', 1, 'Which TWO sources will the students use for their presentation?', 'Choose TWO letters, A–D.', 'listening/m04/part-3/full.mp3', '[{"label": "A", "text": "national school nutrition survey"}, {"label": "B", "text": "a local hospital study"}, {"label": "C", "text": "WHO regional report"}, {"label": "D", "text": "a supermarket sales database"}]'::jsonb, 'A', 'detail'),
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'mcq', 2, 'Which TWO sources will the students use for their presentation?', NULL, 'listening/m04/part-3/full.mp3', '[{"label": "A", "text": "national school nutrition survey"}, {"label": "B", "text": "a local hospital study"}, {"label": "C", "text": "WHO regional report"}, {"label": "D", "text": "a supermarket sales database"}]'::jsonb, 'C', 'detail'),
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'mcq', 3, 'How do the students frame the relationship between menu reform and nutrition education?', 'Choose the correct letter, A, B or C.', 'listening/m04/part-3/full.mp3', '[{"label": "A", "text": "Menu reform is more effective"}, {"label": "B", "text": "The two are complementary"}, {"label": "C", "text": "Education is more effective"}]'::jsonb, 'B', 'detail'),
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'sentence_completion', 4, 'Student 1 covers: introduction, survey data, ___', 'Complete the notes below. Write NO MORE THAN TWO WORDS for each answer.', 'listening/m04/part-3/full.mp3', NULL, 'literature review', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'sentence_completion', 5, 'Case study country: ___', NULL, 'listening/m04/part-3/full.mp3', NULL, 'Sweden', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'sentence_completion', 6, 'Tracking period: ___', NULL, 'listening/m04/part-3/full.mp3', NULL, 'two years/2 years', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'sentence_completion', 7, 'Visual for sugar data: a ___', NULL, 'listening/m04/part-3/full.mp3', NULL, 'bar chart', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'sentence_completion', 8, 'Submission date: ___', NULL, 'listening/m04/part-3/full.mp3', NULL, '21st/twenty-first/twenty first', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'sentence_completion', 9, 'Next meeting location: ___', NULL, 'listening/m04/part-3/full.mp3', NULL, 'library/the library', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 3, 'sentence_completion', 10, 'Student 1 to bring: ___', NULL, 'listening/m04/part-3/full.mp3', NULL, 'laptop', 'completion');
