-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000004

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'listening' AND part = 4
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000004' AND module = 'listening' AND part = 4;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 1, 'international (31) ___', 'Complete the summary below. Write ONE WORD ONLY for each answer.', 'listening/m04/part-4/full.mp3', NULL, 'concern', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 2, 'negotiated in (32) ___', NULL, 'listening/m04/part-4/full.mp3', NULL, 'protocol', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 3, 'near-universal (33) ___', NULL, 'listening/m04/part-4/full.mp3', NULL, 'ratification', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 4, 'greater (34) ___', NULL, 'listening/m04/part-4/full.mp3', NULL, 'responsibility', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 5, 'United States'' (35) ___', NULL, 'listening/m04/part-4/full.mp3', NULL, 'withdrawal', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 6, 'nationally determined (36) ___', NULL, 'listening/m04/part-4/full.mp3', NULL, 'contributions', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 7, 'form of (37) ___', NULL, 'listening/m04/part-4/full.mp3', NULL, 'leverage', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 8, 'enforcement (38) ___', NULL, 'listening/m04/part-4/full.mp3', NULL, 'pathway', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 9, 'breach of (39) ___', NULL, 'listening/m04/part-4/full.mp3', NULL, 'human', 'completion'),
('a0000000-0000-4000-8000-000000000004', 'listening', 4, 'sentence_completion', 10, 'seminar on (40) ___', NULL, 'listening/m04/part-4/full.mp3', NULL, 'climate', 'completion');
