-- BandForge reading seed: Climate Policy & International Agreements
-- mock_test_id = a0000000-0000-4000-8000-000000000005 part = 1

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'reading' AND part = 1
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'reading' AND part = 1;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 1, 1, 'The Kyoto Protocol required binding emissions targets from all participating countries.', 'Climate Policy & International Agreements
A International efforts to coordinate action on climate change date back to the 1992 United Nations Framework Convention on Climate Change, but the most consequential agreement remains the Paris Agreement, adopted in 2015 and entering into force the following year. Unlike its predecessor, the Kyoto Protocol, which imposed binding emissions targets only on developed nations, the Paris Agreement adopted a more flexible architecture: nearly every country submitted its own Nationally Determined Contribution (NDC), a self-set emissions reduction target, with the expectation that these would be strengthened over successive five-year review cycles.
B This shift from binding external targets to voluntary self-determined pledges reflected a pragmatic recognition of political reality. Kyoto''s binding structure had proven difficult to enforce and led several major emitters, including the United States, to withdraw or decline ratification altogether. The Paris framework''s architects gambled that near-universal participation, even with weaker individual commitments, would achieve more than a stricter framework that fewer countries joined. Critics, however, note that current NDCs collectively fall well short of the reductions needed to limit warming to the agreement''s stated goal of well below 2 degrees Celsius above pre-industrial levels.
C A persistent point of contention concerns climate finance — the transfer of funds from wealthier nations to developing countries to support both emissions reduction and adaptation to climate impacts already underway. Developed nations pledged in 2009 to mobilise 100 billion dollars annually by 2020, a target not reliably met until several years after the deadline, according to OECD tracking data. Developing nations argue the figure was inadequate from the outset given the scale of need, while donor countries have faced domestic political pressure that complicates sustained funding commitments.
D The concept of "loss and damage" has emerged as a particularly contentious frontier in climate negotiations. Unlike adaptation funding, which helps countries prepare for future climate impacts, loss and damage refers to compensation for harm already suffered — from rising sea levels submerging coastal communities to crop failures linked to shifting rainfall patterns. Wealthy nations historically resisted formalising loss and damage mechanisms, partly from concern that doing so could establish a precedent for open-ended liability. A breakthrough occurred at the 2022 COP27 summit in Egypt, where a dedicated loss and damage fund was agreed in principle, though the mechanics of contribution and disbursement remained unresolved for subsequent negotiations to settle.
E Some economists argue that the entire framing of climate agreements as multilateral negotiations understates the role that unilateral domestic policy plays in driving global change. China''s dominance in solar panel manufacturing, for instance, emerged largely from domestic industrial policy rather than international agreement, yet it has done more to reduce the global cost of solar energy than most negotiated commitments. This suggests that international agreements may function less as the primary driver of emissions reduction and more as a coordinating signal that shapes expectations, investment decisions, and domestic political feasibility across participating nations.
F Looking toward future negotiation cycles, most observers expect the central tension to persist: the gap between the ambition required by climate science and the ambition politically achievable within domestic constraints in most participating nations. Whether the Paris framework''s iterative, voluntary structure proves capable of closing that gap over successive review cycles, or whether it requires fundamental redesign, remains one of the most consequential open questions in international governance.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 2, 1, 'The Paris Agreement was designed on the assumption that broad participation with weaker pledges would outperform a stricter agreement with fewer members.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 3, 1, 'Current Nationally Determined Contributions are sufficient to meet the Paris Agreement''s temperature goal.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 4, 1, 'The 100-billion-dollar annual climate finance target was met on schedule in 2020.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 5, 1, 'Loss and damage funding is intended to address harm that has already occurred, unlike adaptation funding.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 6, 1, 'China''s solar manufacturing dominance resulted primarily from an international agreement.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 7, 1, 'The Paris Agreement replaced binding targets with self-set pledges known as 7 ……………. ______________', NULL, NULL, 'Nationally Determined Contributions/NDCs/nationally determined contributions', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 8, 1, 'A major ongoing dispute involves 8 …………… ______________', NULL, NULL, 'climate finance', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 9, 1, 'A newer and more contentious issue is 9 …………… ______________', NULL, NULL, 'loss and damage', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 10, 1, 'Some economists argue that 10 …………… policy may be the more powerful driver of global emissions change. ______________', NULL, NULL, 'domestic/unilateral domestic/domestic industrial', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 11, 1, 'At which summit was a loss and damage fund agreed in principle? ______________', NULL, NULL, 'COP27', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 12, 1, 'What does the passage say international agreements may primarily function as, rather than the main driver of emissions reduction? ______________', NULL, NULL, 'coordinating signal/a coordinating signal', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 13, 1, 'What is identified as the central tension expected to persist in future negotiation cycles? ______________', NULL, NULL, 'gap between ambition and feasibility/ambition and feasibility/gap between ambition', 'sentence_completion');
