-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000005

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'listening' AND part = 3
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'listening' AND part = 3;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 1, 'Induction loop sensors detect a ___', 'Write ONE WORD ONLY for each answer.', 'listening/m05/part-3/full.mp3', NULL, 'vehicle', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 2, 'Data sent to local control ___', NULL, 'listening/m05/part-3/full.mp3', NULL, 'cabinet', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 3, 'Forwarded to central traffic management ___', NULL, 'listening/m05/part-3/full.mp3', NULL, 'centre', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 4, 'Compared against historical ___', NULL, 'listening/m05/part-3/full.mp3', NULL, 'patterns', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 5, 'If congestion found → adjustment sent to affected ___', NULL, 'listening/m05/part-3/full.mp3', NULL, 'junction', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 6, 'Full loop completes within ___', NULL, 'listening/m05/part-3/full.mp3', NULL, '90/ninety', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 7, 'Manual override bypasses automated ___', NULL, 'listening/m05/part-3/full.mp3', NULL, 'calculation', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 8, 'Emergency vehicles trigger green light via receiver near the ___', NULL, 'listening/m05/part-3/full.mp3', NULL, 'signal', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 9, 'Data feeds into monthly report → identifies ___', NULL, 'listening/m05/part-3/full.mp3', NULL, 'infrastructure', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 3, 'sentence_completion', 10, 'Report published for ___', NULL, 'listening/m05/part-3/full.mp3', NULL, 'transparency', 'completion');
