-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000005

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'listening' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'listening' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'mcq', 1, 'Which day do winter sessions move to?', 'Choose the correct letter, A, B or C.', 'listening/m05/part-2/full.mp3', '[{"label": "A", "text": "Monday"}, {"label": "B", "text": "Wednesday"}, {"label": "C", "text": "Thursday"}]'::jsonb, 'B', 'detail'),
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'mcq', 2, 'What type of telescope is the main dome instrument?', NULL, 'listening/m05/part-2/full.mp3', '[{"label": "A", "text": "reflector"}, {"label": "B", "text": "refractor"}, {"label": "C", "text": "radio"}]'::jsonb, 'A', 'detail'),
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'mcq', 3, 'Who must accompany members under sixteen at outdoor sessions?', NULL, 'listening/m05/part-2/full.mp3', '[{"label": "A", "text": "another junior member"}, {"label": "B", "text": "the coordinator only"}, {"label": "C", "text": "an adult member"}]'::jsonb, 'C', 'detail'),
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'mcq', 4, 'Where are weather cancellations posted?', NULL, 'listening/m05/part-2/full.mp3', '[{"label": "A", "text": "the noticeboard"}, {"label": "B", "text": "social media"}, {"label": "C", "text": "by text message"}]'::jsonb, 'A', 'detail'),
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'sentence_completion', 5, 'Membership costs fifteen pounds per ___ .', 'Write ONE WORD ONLY.', 'listening/m05/part-2/full.mp3', NULL, 'term', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'matching', 6, 'Beginner sessions', 'Match each activity to when it takes place.', 'listening/m05/part-2/full.mp3', '[{"label": "A", "text": "First Tuesday of the month"}, {"label": "B", "text": "Last Friday of the month"}, {"label": "C", "text": "New moon nights"}]'::jsonb, 'A', 'matching'),
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'matching', 7, 'Deep-sky observation nights', NULL, 'listening/m05/part-2/full.mp3', '[{"label": "A", "text": "First Tuesday of the month"}, {"label": "B", "text": "Last Friday of the month"}, {"label": "C", "text": "New moon nights"}]'::jsonb, 'C', 'matching'),
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'matching', 8, 'Photography sessions', NULL, 'listening/m05/part-2/full.mp3', '[{"label": "A", "text": "First Tuesday of the month"}, {"label": "B", "text": "Last Friday of the month"}, {"label": "C", "text": "New moon nights"}]'::jsonb, 'B', 'matching'),
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'sentence_completion', 9, 'The main telescope requires a ___ member present.', 'Write ONE WORD ONLY for each answer.', 'listening/m05/part-2/full.mp3', NULL, 'committee', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 2, 'sentence_completion', 10, 'Personal equipment can be checked or ___ at sessions.', NULL, 'listening/m05/part-2/full.mp3', NULL, 'calibrated', 'completion');
