-- BandForge reading seed: Genetics, Heredity & Modern Medicine
-- mock_test_id = a0000000-0000-4000-8000-000000000005 part = 3

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'reading' AND part = 3
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'reading' AND part = 3;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 27, 3, 'Progress in genomic medicine has matched the early optimistic projections made after the Human Genome Project.', 'Genetics, Heredity & Modern Medicine
A The completion of the Human Genome Project in 2003 was widely anticipated to usher in an era of personalised medicine, in which treatments would be tailored to an individual''s genetic profile with unprecedented precision. Two decades later, the field of genomic medicine has advanced substantially, but progress has proven more incremental and more complicated than the early, more optimistic projections suggested, illuminating both the promise and the considerable difficulty of translating genetic knowledge into clinical practice.
B Monogenic disorders — conditions caused by mutations in a single gene, such as cystic fibrosis and sickle cell disease — have seen the most tangible clinical progress. Gene therapies targeting these conditions, including CRISPR-based treatments approved in the early 2020s, have demonstrated the ability to correct the underlying genetic mutation in some patients, representing a functional cure rather than symptom management. However, monogenic disorders collectively account for a relatively small proportion of overall disease burden compared with polygenic conditions, where genetic risk is distributed across hundreds or thousands of individual gene variants, each contributing a small effect.
C Polygenic conditions, which include most common diseases such as type 2 diabetes, heart disease, and many psychiatric conditions, have proven considerably more resistant to straightforward genetic intervention. Polygenic risk scores, which aggregate the effects of many genetic variants into a single risk estimate, have shown some predictive value at the population level but remain notably less reliable for individual patients, particularly given that these scores were developed predominantly using genetic data from populations of European ancestry, limiting their accuracy when applied to individuals from other genetic backgrounds.
D This ancestry bias in genomic databases represents one of the field''s most significant unresolved challenges. Large-scale genomic databases such as the UK Biobank and various national genome projects have historically drawn disproportionately from populations of European descent, meaning that genetic variants more common in other populations remain comparatively understudied. Left uncorrected, this imbalance risks entrenching existing health disparities, as genomic medicine tools calibrated on unrepresentative data may prove systematically less accurate for the populations that stand to benefit most from expanded diagnostic and preventive capability.
E Beyond purely technical challenges, genomic medicine raises ethical questions with few settled answers. Direct-to-consumer genetic testing has made ancestry and health-risk information widely accessible, but genetic counsellors report that many consumers struggle to interpret probabilistic risk information appropriately, sometimes overreacting to modest elevated risks or, conversely, dismissing genuinely significant findings that warrant clinical follow-up. The question of genetic privacy has also grown more urgent as testing companies build databases that could, in principle, be accessed by insurers, employers, or law enforcement, prompting several jurisdictions to introduce specific legal protections against genetic discrimination.
F Looking forward, most researchers in the field describe the current period as one of consolidation rather than revolution: refining existing tools, expanding the diversity of genomic databases, and developing more rigorous frameworks for translating population-level genetic findings into individually meaningful clinical guidance. The transformative potential once promised for genomic medicine has not disappeared, researchers generally maintain, but its realisation is proving to be a considerably longer and more incremental process than initial projections following the Human Genome Project anticipated.', '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 28, 3, 'Gene therapies for monogenic disorders can, in some cases, correct the underlying genetic mutation.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 29, 3, 'Monogenic disorders account for the majority of overall global disease burden.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 30, 3, 'Polygenic risk scores are equally reliable across all ancestral populations.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 31, 3, 'Genomic databases have historically overrepresented populations of European descent.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'tfng', 32, 3, 'Legal protections against genetic discrimination have been introduced in some jurisdictions.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 33, 3, 'Genetic variants aggregated into a ___ ______________', NULL, NULL, 'polygenic risk score', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 34, 3, 'Shows predictive value at the ___ level ______________', NULL, NULL, 'population', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 35, 3, 'Less reliable for ___ patients ______________', NULL, NULL, 'individual', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 36, 3, 'Particularly limited for those outside ___ ancestry data ______________', NULL, NULL, 'European', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 37, 3, 'Genetic counsellors report that consumers sometimes struggle to interpret ……………… appropriately. ______________', NULL, NULL, 'probabilistic risk information', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 38, 3, 'Databases built by testing companies could, in principle, be accessed by insurers, employers, or ………………. ______________', NULL, NULL, 'law enforcement', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 39, 3, 'Researchers describe the current period in genomic medicine as one of ……………… rather than revolution. ______________', NULL, NULL, 'consolidation', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 40, 3, 'The realisation of genomic medicine''s potential is proving to be a longer and more ……………… process than first anticipated. ______________', NULL, NULL, 'incremental', 'sentence_completion');
