-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000005

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'listening' AND part = 1
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'listening' AND part = 1;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 1, 'Surname', 'Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.

@@form_title@@OUTPATIENT REGISTRATION FORM', 'listening/m05/part-1/full.mp3', NULL, 'Okafor', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 2, 'Date of birth', NULL, 'listening/m05/part-1/full.mp3', NULL, '14 March 1989/14/03/1989/14th March 1989', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 3, 'Contact number', NULL, 'listening/m05/part-1/full.mp3', NULL, '0181 499 2206/01814992206', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 4, 'Known allergy', NULL, 'listening/m05/part-1/full.mp3', NULL, 'penicillin', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 5, 'Current medication for', NULL, 'listening/m05/part-1/full.mp3', NULL, 'blood pressure', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 6, 'Preferred clinic day', NULL, 'listening/m05/part-1/full.mp3', NULL, 'Thursday', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 7, 'Appointment time', NULL, 'listening/m05/part-1/full.mp3', NULL, '10:30/10.30', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 8, 'Preliminary check', NULL, 'listening/m05/part-1/full.mp3', NULL, 'ECG', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 9, 'Patient reference', NULL, 'listening/m05/part-1/full.mp3', NULL, 'P44199', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 1, 'form_completion', 10, 'Emergency contact', NULL, 'listening/m05/part-1/full.mp3', NULL, 'Adaeze Okafor', 'completion');
