-- Generated by normalize_listening_mock.py — review before applying
-- mock_test_id = a0000000-0000-4000-8000-000000000005

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'listening' AND part = 4
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'listening' AND part = 4;

INSERT INTO questions (
  mock_test_id, module, part, question_type, question_number, prompt,
  passage_text, audio_url, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 1, 'Post-war supply chain strategy prioritised cost minimisation through global ___', 'Complete the summary below. Write ONE WORD ONLY for each answer.', 'listening/m05/part-4/full.mp3', NULL, 'specialisation', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 2, 'just-in-time inventory that assumed shipments would arrive exactly when ___', NULL, 'listening/m05/part-4/full.mp3', NULL, 'needed', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 3, 'disruption could spread across an entire global ___', NULL, 'listening/m05/part-4/full.mp3', NULL, 'network', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 4, 'favouring resilience over pure ___', NULL, 'listening/m05/part-4/full.mp3', NULL, 'efficiency', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 5, 'which reduces reliance on long-distance ___', NULL, 'listening/m05/part-4/full.mp3', NULL, 'shipping', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 6, 'maintaining multiple ___', NULL, 'listening/m05/part-4/full.mp3', NULL, 'suppliers', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 7, 'treating semiconductors as a matter of national ___', NULL, 'listening/m05/part-4/full.mp3', NULL, 'security', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 8, 'fragment trade into competing regional ___', NULL, 'listening/m05/part-4/full.mp3', NULL, 'blocs', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 9, 'see it as the price of ___', NULL, 'listening/m05/part-4/full.mp3', NULL, 'resilience', 'completion'),
('a0000000-0000-4000-8000-000000000005', 'listening', 4, 'sentence_completion', 10, 'next week''s ___', NULL, 'listening/m05/part-4/full.mp3', NULL, 'seminar', 'completion');
