-- BandForge reading seed: Global Trade & Emerging Markets
-- mock_test_id = a0000000-0000-4000-8000-000000000005 part = 2

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'reading' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000005' AND module = 'reading' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000005', 'reading', 'matching_headings', 14, 2, 'Paragraph B', 'Global Trade & Emerging Markets
A For much of the postwar era, global trade policy was shaped by a broad consensus favouring reduced tariffs and increasing economic integration, formalised through institutions such as the General Agreement on Tariffs and Trade and, later, the World Trade Organization. This consensus has fractured markedly over the past decade, as concerns over domestic manufacturing decline, supply chain vulnerability, and geopolitical rivalry have pushed several major economies toward more protectionist and interventionist trade policies.
B Emerging markets occupy a particularly complex position within this shifting landscape. Countries such as Vietnam, India, and Mexico have benefited substantially from a strategy sometimes termed "China plus one," whereby multinational corporations diversify manufacturing operations away from exclusive reliance on China, partly in response to rising Chinese labour costs and partly to reduce geopolitical exposure. Vietnam''s export sector, for instance, grew at a considerably faster rate than the regional average over the past decade, with electronics assembly becoming a particularly significant component of that growth.
C This diversification, however, has not been uniformly beneficial. Economists distinguish between genuine manufacturing capability development and what some term "transhipment," where goods are merely routed through a third country with minimal value added, primarily to circumvent tariffs imposed on direct imports from the original manufacturing source. Distinguishing between these two categories has become a significant point of contention in trade disputes, with several countries facing accusations of allowing transhipment at a scale that undermines the stated purpose of tariff policy.
D A further complication involves currency dynamics. Emerging market economies with significant dollar-denominated debt face acute vulnerability during periods of dollar strength, as debt servicing costs rise in local-currency terms even without any change in the underlying debt obligation. This dynamic has historically preceded several emerging market financial crises, and current account deficits combined with substantial foreign-currency borrowing remain closely monitored indicators among investors and multilateral lenders alike, given their historical association with sudden capital flight.
E Trade economists increasingly emphasise that the benefits of export-led growth strategies depend heavily on complementary domestic investment in infrastructure, education, and institutional capacity. Countries that successfully translated export growth into broader development, such as South Korea in earlier decades, typically paired trade openness with substantial state investment in these areas. By contrast, countries that rely primarily on low labour costs without corresponding investment risk remaining locked into low-value-added manufacturing roles within global supply chains, vulnerable to displacement the moment an even lower-cost alternative emerges elsewhere.
F The longer-term trajectory of global trade remains genuinely uncertain. Some economists argue that current protectionist trends represent a temporary correction following decades of rapid globalisation, while others contend they signal a more durable structural shift toward regionalised trade blocs organised around geopolitical alignment rather than pure economic efficiency. Emerging markets navigating this uncertainty face the difficult task of positioning themselves advantageously within a system whose fundamental rules may look markedly different a decade from now.', '[{"label": "i", "text": "The risks of currency exposure in emerging economies"}, {"label": "ii", "text": "Genuine growth versus tariff circumvention"}, {"label": "iii", "text": "Uncertain long-term direction of global trade"}, {"label": "iv", "text": "Beneficiaries of manufacturing diversification away from China"}, {"label": "v", "text": "The historical consensus favouring free trade"}, {"label": "vi", "text": "Why export growth alone does not guarantee development"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'matching_headings', 15, 2, 'Paragraph C', NULL, '[{"label": "i", "text": "The risks of currency exposure in emerging economies"}, {"label": "ii", "text": "Genuine growth versus tariff circumvention"}, {"label": "iii", "text": "Uncertain long-term direction of global trade"}, {"label": "iv", "text": "Beneficiaries of manufacturing diversification away from China"}, {"label": "v", "text": "The historical consensus favouring free trade"}, {"label": "vi", "text": "Why export growth alone does not guarantee development"}]'::jsonb, 'ii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'matching_headings', 16, 2, 'Paragraph D', NULL, '[{"label": "i", "text": "The risks of currency exposure in emerging economies"}, {"label": "ii", "text": "Genuine growth versus tariff circumvention"}, {"label": "iii", "text": "Uncertain long-term direction of global trade"}, {"label": "iv", "text": "Beneficiaries of manufacturing diversification away from China"}, {"label": "v", "text": "The historical consensus favouring free trade"}, {"label": "vi", "text": "Why export growth alone does not guarantee development"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'matching_headings', 17, 2, 'Paragraph E', NULL, '[{"label": "i", "text": "The risks of currency exposure in emerging economies"}, {"label": "ii", "text": "Genuine growth versus tariff circumvention"}, {"label": "iii", "text": "Uncertain long-term direction of global trade"}, {"label": "iv", "text": "Beneficiaries of manufacturing diversification away from China"}, {"label": "v", "text": "The historical consensus favouring free trade"}, {"label": "vi", "text": "Why export growth alone does not guarantee development"}]'::jsonb, 'vi', 'matching_headings'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'matching_headings', 18, 2, 'Paragraph F', NULL, '[{"label": "i", "text": "The risks of currency exposure in emerging economies"}, {"label": "ii", "text": "Genuine growth versus tariff circumvention"}, {"label": "iii", "text": "Uncertain long-term direction of global trade"}, {"label": "iv", "text": "Beneficiaries of manufacturing diversification away from China"}, {"label": "v", "text": "The historical consensus favouring free trade"}, {"label": "vi", "text": "Why export growth alone does not guarantee development"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 19, 2, '"China plus one": Multinationals diversify away from 19 …………… manufacturing reliance ______________', NULL, NULL, 'Chinese/China/exclusive Chinese', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 20, 2, 'Transhipment: Goods routed through a third country to avoid 20 …………… ______________', NULL, NULL, 'tariffs', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 21, 2, 'Dollar-denominated debt risk: Rising 21 …………… costs during periods of dollar strength ______________', NULL, NULL, 'debt servicing', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 22, 2, 'South Korea''s model: Trade openness paired with state investment in infrastructure, education, and 22 …………… ______________', NULL, NULL, 'institutional capacity', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 23, 2, 'Which country''s export sector is cited as having grown faster than the regional average? ______________', NULL, NULL, 'Vietnam''s/Vietnam', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 24, 2, 'What indicator, alongside dollar-denominated borrowing, is closely monitored by investors and lenders? ______________', NULL, NULL, 'current account deficits', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 25, 2, 'What kind of manufacturing roles do countries risk remaining locked into without complementary investment? ______________', NULL, NULL, 'low-value-added/low value added', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000005', 'reading', 'sentence_completion', 26, 2, 'What do some economists believe current protectionist trends might signal, aside from a temporary correction? ______________', NULL, NULL, 'structural shift/a structural shift', 'sentence_completion');
