#!/usr/bin/env bash
# Phase 1A: local Supabase for low-latency dev (replaces remote HTTPS round-trips).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ENV_LOCAL="$ROOT/.env.local"
ENV_EXAMPLE="$ROOT/env.local.example"

red() { printf '\033[0;31m%s\033[0m\n' "$*"; }
green() { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[1;33m%s\033[0m\n' "$*"; }

need_cli() {
  if ! command -v supabase >/dev/null 2>&1; then
    red "Supabase CLI not found."
    echo "Install: brew install supabase/tap/supabase"
    echo "Docs:    backend/docs/LOCAL_SUPABASE.md"
    exit 1
  fi
}

need_docker() {
  if ! docker info >/dev/null 2>&1; then
    red "Docker is not running. Start Docker Desktop, then retry."
    exit 1
  fi
}

cmd_start() {
  need_cli
  need_docker
  yellow "Starting local Supabase (first run may pull images — a few minutes)..."
  supabase start
  cmd_sync_env
  green "Local Supabase is up."
  echo ""
  supabase status
  echo ""
  yellow "Backend loads backend/.env then overrides with backend/.env.local"
  yellow "Restart uvicorn after sync. Verify: python scripts/verify_schema.py"
}

cmd_stop() {
  need_cli
  supabase stop
  green "Stopped."
}

cmd_reset() {
  need_cli
  need_docker
  yellow "Resetting DB and re-applying all migrations in supabase/migrations/ ..."
  supabase db reset
  cmd_sync_env
  green "Reset complete. Run: python scripts/verify_schema.py"
}

cmd_status() {
  need_cli
  supabase status
}

# Write backend/.env.local from `supabase status -o env` (Supabase keys only).
cmd_sync_env() {
  need_cli
  if ! supabase status >/dev/null 2>&1; then
    red "Local Supabase is not running. Run: ./scripts/local_supabase.sh start"
    exit 1
  fi

  local tmp
  tmp="$(mktemp)"
  supabase status -o env >"$tmp"

  # shellcheck disable=SC1090
  set -a
  # shellcheck source=/dev/null
  source "$tmp"
  set +a
  rm -f "$tmp"

  if [[ -z "${API_URL:-}" || -z "${SERVICE_ROLE_KEY:-}" ]]; then
    red "Could not read API_URL / SERVICE_ROLE_KEY from supabase status."
    exit 1
  fi

  cat >"$ENV_LOCAL" <<EOF
# Generated by ./scripts/local_supabase.sh sync — overrides remote Supabase in .env
# Remove this file or run without .env.local to use cloud Supabase again.

SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
SUPABASE_SECRET_KEY=${SERVICE_ROLE_KEY}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY:-}

# Optional: mark dev DB in logs
SUPABASE_LOCAL=true
EOF

  green "Wrote $ENV_LOCAL"
}

cmd_cloud() {
  if [[ -f "$ENV_LOCAL" ]]; then
    rm -f "$ENV_LOCAL"
    green "Removed $ENV_LOCAL — backend uses cloud keys from .env again."
  else
    yellow "No .env.local present; already using .env only."
  fi
  echo "Restart uvicorn (and Next.js if needed)."
}

# Restore a prod/staging dump into local Docker Postgres, then anonymize Tier 1 PII.
# Plain `reset` stays migration-only (no PII). Use import-dump when loading real data.
cmd_import_dump() {
  need_cli
  need_docker
  local dump="${1:-}"
  if [[ -z "$dump" ]]; then
    red "Usage: ./scripts/local_supabase.sh import-dump <dump.dump|dump.sql>"
    exit 1
  fi
  if [[ ! -f "$dump" ]]; then
    red "Dump not found: $dump"
    exit 1
  fi
  if ! supabase status >/dev/null 2>&1; then
    yellow "Local Supabase not running — starting …"
    cmd_start
  else
    cmd_sync_env
  fi

  local db_url
  db_url="$(supabase status -o env 2>/dev/null | sed -n 's/^DB_URL=//p' | tr -d '"' | head -1)"
  if [[ -z "$db_url" ]]; then
    # Fallback matches default local stack from config.toml
    db_url="postgresql://postgres:postgres@127.0.0.1:54322/postgres"
  fi

  yellow "Importing $dump into local DB …"
  case "$dump" in
    *.sql)
      psql "$db_url" -v ON_ERROR_STOP=1 -f "$dump"
      ;;
    *.sql.gz)
      gzip -dc "$dump" | psql "$db_url" -v ON_ERROR_STOP=1
      ;;
    *)
      pg_restore --no-owner --no-acl --clean --if-exists -d "$db_url" "$dump" \
        || yellow "pg_restore exited non-zero (often role/ACL noise); continuing to anonymize"
      ;;
  esac

  green "Import finished. Enabling Tier 1 PII masking …"
  # Ensure .env.local is loaded by anonymize script (SUPABASE_LOCAL=true)
  export SUPABASE_LOCAL=true
  # shellcheck disable=SC1090
  set -a
  # shellcheck source=/dev/null
  source "$ENV_LOCAL"
  set +a

  local python_bin="python3"
  if [[ -x "$ROOT/.venv/bin/python" ]]; then
    python_bin="$ROOT/.venv/bin/python"
  fi

  "$python_bin" -m scripts.anonymize_tier1_pii \
    --enable \
    --backfill \
    --verify \
    --i-understand-nonprod

  green "Local import + Tier 1 masking complete. Triggers stay on for new writes."
}

cmd_help() {
  cat <<EOF
Usage: ./scripts/local_supabase.sh <command>

  start         Start Docker Supabase + write .env.local
  stop          Stop local stack
  reset         Drop DB, re-run all migrations (clean seed — no PII)
  import-dump   Restore a dump into local DB, then enable + backfill Tier 1 PII masking
  status        Show URLs and keys
  sync          Refresh .env.local from running stack
  cloud         Remove .env.local (switch back to remote .env)
  help          This message

First-time setup: see backend/docs/LOCAL_SUPABASE.md
PII masking:      see backend/docs/PII_MASKING.md
EOF
}

case "${1:-start}" in
  start) cmd_start ;;
  stop) cmd_stop ;;
  reset) cmd_reset ;;
  import-dump) cmd_import_dump "${2:-}" ;;
  status) cmd_status ;;
  sync) cmd_sync_env ;;
  cloud) cmd_cloud ;;
  help|-h|--help) cmd_help ;;
  *)
    red "Unknown command: $1"
    cmd_help
    exit 1
    ;;
esac
