"""Speaking module constants."""

SPEAKING_DURATION_MINUTES = 14
SPEAKING_PART1_RECORD_SECONDS = 120
# Max time to answer a Part 1 question before auto-advancing (testing-friendly).
SPEAKING_PART1_MAX_RECORDING_SECONDS = 60 * 60
SPEAKING_PART2_MAX_RECORDING_SECONDS = 120
SPEAKING_PART3_MAX_RECORDING_SECONDS = 60
