-- M01 Reading Passage 2: When the Rainforests of the Sea Fall Silent (examiner pack, word-for-word)

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions
  WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000001'
    AND module = 'reading'
    AND part = 2
);

DELETE FROM questions
WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000001'
  AND module = 'reading'
  AND part = 2;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 1, 2, 'Coral reefs cover under one per cent of the ocean floor yet host about a quarter of all marine species.', 'When the Rainforests of the Sea Fall Silent

A    Coral reefs occupy a curious place in the natural world. Although they cover less than one per cent of the ocean floor, they provide a home for roughly a quarter of all marine species, an extraordinary concentration of life that has earned them the nickname "the rainforests of the sea". Few environments on Earth pack so much biological diversity into so small an area. This abundance is not accidental. Reefs are built over thousands of years by colonies of tiny animals called polyps, which secrete limestone skeletons that accumulate into vast and intricate structures. The result is a habitat of remarkable complexity, offering shelter, breeding grounds and feeding opportunities to creatures ranging from microscopic plankton to large predatory fish.

B    The vitality of a reef depends on an unusual partnership. Coral polyps share their tissues with single-celled algae known as zooxanthellae, which use sunlight to produce energy through photosynthesis. The algae supply the coral with most of its food and give reefs their brilliant colours; in return, they receive shelter and a steady supply of nutrients. This relationship, however, is delicate. When water temperatures rise even slightly above the normal seasonal maximum, the algae become harmful to their hosts, and the corals expel them. Stripped of their algae, the corals turn a ghostly white — a process known as bleaching. A bleached coral is not yet dead, but it is starving, and if conditions do not improve it will not survive.

C    The scale of recent bleaching has alarmed scientists. In 2016, an exceptionally warm year, the northern section of Australia''s Great Barrier Reef experienced the most severe bleaching ever recorded there. A widely cited study led by Terry Hughes of the ARC Centre of Excellence for Coral Reef Studies found that around two-thirds of corals in the worst-affected northern stretch died within months. What disturbed researchers most was not the bleaching itself but its frequency: reefs that once had decades to recover between such events are now being struck again within a few years, leaving little time for regeneration.

D    Warming is not the only threat carried by a changing atmosphere. The oceans absorb a substantial share of the carbon dioxide released by human activity, and as that gas dissolves it makes seawater steadily more acidic. This shift in chemistry makes it harder for corals to build and maintain their limestone skeletons, slowing their growth and weakening existing structures. Acidification works quietly, without the dramatic visual signal of bleaching, but over time it undermines the very foundation on which a reef is constructed.

E    Climate change has tended to dominate public discussion, yet reefs face an array of more local pressures. Overfishing removes the species that graze on algae and would otherwise keep it from smothering young corals. Run-off from farmland carries fertilisers and sediment that cloud the water and block the sunlight the algae need. Coastal development, dredging and pollution add further strain. Individually, none of these may be fatal; together, they erode a reef''s capacity to withstand and recover from heat stress, a quality scientists term resilience.

F    The consequences of reef decline extend well beyond the loss of natural beauty. Reefs act as natural breakwaters, absorbing wave energy and protecting low-lying coastlines from storms and erosion. They underpin fisheries that feed coastal communities and support tourism industries worth billions of dollars each year. According to some estimates, around half a billion people worldwide depend on reefs for food, income or coastal protection. The collapse of these ecosystems would therefore represent not only an ecological catastrophe but a profound economic and humanitarian one.

G    The outlook is sobering. The Intergovernmental Panel on Climate Change has projected that even if global warming is held to 1.5 degrees Celsius, between seventy and ninety per cent of the world''s reefs are likely to disappear; at 2 degrees, the loss would be almost total. Yet researchers have not abandoned hope. Some corals have shown a surprising tolerance of heat, and scientists are studying these survivors in an effort to identify and propagate hardier strains, an approach sometimes called assisted evolution. Such interventions cannot substitute for reducing emissions, but they may buy time. Reefs, in other words, are not beyond saving — but the window in which they can be saved is narrowing rapidly.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 2, 2, 'Bleaching causes the immediate death of the affected corals.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 3, 2, 'In the worst-affected northern part of the Great Barrier Reef, around two-thirds of corals died within months of the 2016 bleaching.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 4, 2, 'Ocean acidification produces visible warning signs similar to those of bleaching.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 5, 2, 'Assisted evolution programmes have already restored several reefs to their original condition.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NOT GIVEN', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'matching_headings', 6, 2, 'Paragraph D', NULL, '[{"label": "i", "text": "The mechanics of building a reef"}, {"label": "ii", "text": "A second, less visible danger from carbon dioxide"}, {"label": "iii", "text": "How a vital biological partnership functions"}, {"label": "iv", "text": "Threats that originate closer to shore"}, {"label": "v", "text": "Why bleaching events are becoming more frequent"}, {"label": "vi", "text": "The cost of reef loss to people"}, {"label": "vii", "text": "Grim forecasts tempered by emerging solutions"}]'::jsonb, 'ii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'matching_headings', 7, 2, 'Paragraph E', NULL, '[{"label": "i", "text": "The mechanics of building a reef"}, {"label": "ii", "text": "A second, less visible danger from carbon dioxide"}, {"label": "iii", "text": "How a vital biological partnership functions"}, {"label": "iv", "text": "Threats that originate closer to shore"}, {"label": "v", "text": "Why bleaching events are becoming more frequent"}, {"label": "vi", "text": "The cost of reef loss to people"}, {"label": "vii", "text": "Grim forecasts tempered by emerging solutions"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'matching_headings', 8, 2, 'Paragraph F', NULL, '[{"label": "i", "text": "The mechanics of building a reef"}, {"label": "ii", "text": "A second, less visible danger from carbon dioxide"}, {"label": "iii", "text": "How a vital biological partnership functions"}, {"label": "iv", "text": "Threats that originate closer to shore"}, {"label": "v", "text": "Why bleaching events are becoming more frequent"}, {"label": "vi", "text": "The cost of reef loss to people"}, {"label": "vii", "text": "Grim forecasts tempered by emerging solutions"}]'::jsonb, 'vi', 'matching_headings'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'matching_headings', 9, 2, 'Paragraph G', NULL, '[{"label": "i", "text": "The mechanics of building a reef"}, {"label": "ii", "text": "A second, less visible danger from carbon dioxide"}, {"label": "iii", "text": "How a vital biological partnership functions"}, {"label": "iv", "text": "Threats that originate closer to shore"}, {"label": "v", "text": "Why bleaching events are becoming more frequent"}, {"label": "vi", "text": "The cost of reef loss to people"}, {"label": "vii", "text": "Grim forecasts tempered by emerging solutions"}]'::jsonb, 'vii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'sentence_completion', 10, 2, 'The brilliant colours of a reef are produced by the algae known as ______.', NULL, NULL, 'zooxanthellae', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'sentence_completion', 11, 2, 'Scientists use the term ______ to describe a reef''s capacity to withstand and recover from heat stress.', NULL, NULL, 'resilience', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'sentence_completion', 12, 2, 'By absorbing wave energy, reefs function as natural ______ that shield low-lying coastlines.', NULL, NULL, 'breakwaters', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'sentence_completion', 13, 2, 'The practice of breeding hardier corals from heat-tolerant survivors is sometimes referred to as ______.', NULL, NULL, 'assisted evolution', 'sentence_completion');
