-- MT2 Reading P2 alignment — founder source (paragraphs E-F, completion 10-13).

-- BandForge reading seed: The Unfulfilled Promise of Educational Technology
-- mock_test_id = a0000000-0000-4000-8000-000000000002 part = 2

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 1, 2, 'Predictions that new technologies would transform education have a long history.', 'The Unfulfilled Promise of Educational Technology

A    For more than a century, each new communication technology has arrived in classrooms accompanied by bold predictions. In the 1920s, the inventor Thomas Edison declared that motion pictures would soon replace textbooks; later, radio, television, and the personal computer were each described as forces that would transform how children learn. The pattern has been remarkably consistent: an initial wave of enthusiasm, followed by disappointment as the new tool fails to deliver the promised revolution. Understanding why this cycle repeats has become an important question for researchers, particularly as digital devices now occupy a central place in schools worldwide. The mismatch between confident forecasts and actual classroom results raises a deeper issue: whether the problem lies in the technology itself, or in the assumptions made about what it can achieve.

B    The most recent example of this cycle is the massive open online course, or MOOC. When platforms such as Coursera and edX were launched in 2012, commentators described that period as the "year of the MOOC" and predicted that free, university-level courses would make traditional institutions obsolete. Enrolment figures were indeed enormous, with individual courses attracting hundreds of thousands of registrations. Yet completion told a different story. A widely cited analysis by researchers at the University of Pennsylvania found that, on average, only about four per cent of those who signed up for a course finished it. Most participants, moreover, already held a degree, suggesting that the courses were extending opportunity for the well-educated rather than reaching new learners. By the end of the decade, most universities had quietly accepted that MOOCs would complement campus teaching rather than replace it.

C    Similar gaps between expectation and outcome have appeared in schools. Many governments have invested heavily in schemes to provide every pupil with a laptop or tablet, on the assumption that access to devices would automatically raise achievement. The evidence has been mixed at best. A large 2015 report by the Organisation for Economic Co-operation and Development examined data from dozens of countries and concluded that students who used computers very frequently at school tended to perform worse in reading and mathematics, even after social background was taken into account. The report did not argue that technology was harmful in itself, but it questioned the belief that simply distributing hardware would improve results. What mattered, the authors suggested, was not whether computers were present but how, and how often, they were used.

D    Researchers who study these failures point to a recurring misunderstanding. Technology, they argue, is not a substitute for skilled teaching; it is a tool whose value depends entirely on how it is used. A tablet can display an excellent lesson or a poor one, and a pupil left alone with a device may simply become distracted. There is also evidence of a so-called second digital divide. While access to devices has become more equal, the ability to use them productively has not. Students from advantaged homes are more likely to use technology for learning, whereas those from poorer backgrounds more often use the same devices for entertainment, which can widen rather than narrow existing gaps in attainment.

E    None of this means that technology has no place in education. When it is carefully designed and closely integrated with teaching, it can produce genuine benefits. Adaptive learning software, which adjusts the difficulty of questions to each learner''s performance, has shown modest but consistent gains in subjects such as mathematics. The underlying idea is old: in 1984 the psychologist Benjamin Bloom observed that a student receiving one-to-one tutoring could outperform around ninety-eight per cent of pupils taught in conventional classes, a result he called the "two sigma problem". Personalised software cannot fully reproduce a human tutor, but it can offer some of the individual attention that large classes make impossible. Crucially, the most successful programmes use such software for only part of each lesson, leaving the teacher free to concentrate on pupils who need additional help.

F    The lesson emerging from decades of research is therefore not that educational technology fails, but that it succeeds only under particular conditions. It works best as a support for teachers rather than a replacement for them, and when its introduction is accompanied by training and a clear sense of purpose. The danger lies in treating any new device as a solution in itself. As long as schools focus on the quality of teaching and on how a tool is actually used, technology can make a real contribution. Where it is adopted simply because it is new, the familiar cycle of enthusiasm and disappointment is likely to continue.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 2, 2, 'Individual MOOCs were able to attract very large numbers of registrations.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 3, 2, 'The University of Pennsylvania study found that the majority of MOOC enrolees completed their course.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 4, 2, 'The 2015 OECD report concluded that computers are inherently harmful to learning.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 5, 2, 'Adaptive learning software is now used in most secondary schools.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NOT GIVEN', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 6, 2, 'Paragraph C', NULL, '[{"label": "i", "text": "Hardware alone does not guarantee better results"}, {"label": "ii", "text": "The high cost of modern classroom devices"}, {"label": "iii", "text": "How a lack of understanding limits technology''s value"}, {"label": "iv", "text": "Software that responds to the individual learner"}, {"label": "v", "text": "Technology as a partner to good teaching"}, {"label": "vi", "text": "The decline of the traditional university"}, {"label": "vii", "text": "Why online courses attract so many students"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 7, 2, 'Paragraph D', NULL, '[{"label": "i", "text": "Hardware alone does not guarantee better results"}, {"label": "ii", "text": "The high cost of modern classroom devices"}, {"label": "iii", "text": "How a lack of understanding limits technology''s value"}, {"label": "iv", "text": "Software that responds to the individual learner"}, {"label": "v", "text": "Technology as a partner to good teaching"}, {"label": "vi", "text": "The decline of the traditional university"}, {"label": "vii", "text": "Why online courses attract so many students"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 8, 2, 'Paragraph E', NULL, '[{"label": "i", "text": "Hardware alone does not guarantee better results"}, {"label": "ii", "text": "The high cost of modern classroom devices"}, {"label": "iii", "text": "How a lack of understanding limits technology''s value"}, {"label": "iv", "text": "Software that responds to the individual learner"}, {"label": "v", "text": "Technology as a partner to good teaching"}, {"label": "vi", "text": "The decline of the traditional university"}, {"label": "vii", "text": "Why online courses attract so many students"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 9, 2, 'Paragraph F', NULL, '[{"label": "i", "text": "Hardware alone does not guarantee better results"}, {"label": "ii", "text": "The high cost of modern classroom devices"}, {"label": "iii", "text": "How a lack of understanding limits technology''s value"}, {"label": "iv", "text": "Software that responds to the individual learner"}, {"label": "v", "text": "Technology as a partner to good teaching"}, {"label": "vi", "text": "The decline of the traditional university"}, {"label": "vii", "text": "Why online courses attract so many students"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 10, 2, 'In the 1920s, Thomas Edison predicted that ______ would take the place of textbooks.', NULL, NULL, 'motion pictures', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 11, 2, 'By the end of the decade, universities had accepted that MOOCs would ______ campus teaching rather than replace it.', NULL, NULL, 'complement', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 12, 2, 'The unequal ability to use devices productively is described by researchers as a second ______.', NULL, NULL, 'digital divide', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 13, 2, 'Adaptive learning software changes the ______ of questions according to each learner''s performance.', NULL, NULL, 'difficulty', 'sentence_completion');
