-- MT2 Reading P1 alignment — founder source (paragraph F, TFNG, headings C-F, completion 10-13).

-- BandForge reading seed: How Animals Make Sense of Their World
-- mock_test_id = a0000000-0000-4000-8000-000000000002 part = 1

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 1
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 1;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 1, 1, 'During much of the twentieth century, scientists generally believed that intelligent-seeming animal behaviour was based on instinct.', 'How Animals Make Sense of Their World

A    During much of the twentieth century, scientists were reluctant to credit animals with anything resembling thought. Behaviour that appeared intelligent was usually explained as instinct — fixed responses shaped by evolution rather than genuine reasoning. A barking dog or a nest-building bird was seen as following an inherited programme, not making a decision. This cautious view has gradually given way to a more generous picture. The field known as animal cognition now studies how creatures perceive, remember, and respond to the world around them, drawing on careful observation in the wild as well as controlled laboratory experiments. A growing body of evidence suggests that many species process information in surprisingly flexible ways. Researchers are careful, however, to distinguish between behaviour that merely looks clever and behaviour that genuinely involves understanding, since the two can be difficult to tell apart.

B    Communication has provided some of the most striking examples of this flexibility. The Austrian zoologist Karl von Frisch spent decades decoding the so-called waggle dance of honeybees, a looping movement performed inside the hive that conveys both the direction and the distance of a food source. The angle of the dance indicates direction relative to the sun, while its duration signals how far away the food lies. His work was so influential that he shared the Nobel Prize in 1973. Many years later, the researchers Robert Seyfarth and Dorothy Cheney studied vervet monkeys in East Africa and showed that they use distinct alarm calls for different predators. One sound sends the group climbing into the trees to escape leopards, while another makes them look upward to watch for eagles. The calls function almost like words, each tied to a specific meaning rather than simply expressing fear.

C    Problem-solving offers further evidence of mental flexibility. New Caledonian crows are perhaps the best-studied example. In the wild they shape twigs and leaves into hooks to extract insects from narrow crevices, and in laboratory tests they have solved multi-step puzzles that require using one tool to obtain another. In one widely reported experiment, a captive crow named Betty bent a straight piece of wire into a hook in order to lift a small bucket of food out of a tube — a solution she had never been trained to produce. Although later studies showed that wild crows also bend materials naturally, the birds'' ability to adapt their methods to new situations remains impressive. Such behaviour suggests that they can picture a goal and work out the sequence of steps needed to reach it.

D    Memory, too, can be remarkably sophisticated. Western scrub jays hide thousands of food items across their territory and later recover them with considerable accuracy. Research led by Nicola Clayton at the University of Cambridge demonstrated that these birds remember not only where they stored food but also what they stored and how long ago they did so. Perishable items such as insects are retrieved before they have time to spoil, while longer-lasting seeds may be left for several days. The jays even appear to change their hiding behaviour when other birds are watching, returning later to move the food to a new location. This ability to keep track of specific past events was once thought to be unique to humans.

E    Not every impressive performance withstands close scrutiny, and scientists remain wary of reading too much into animal behaviour. The most famous cautionary tale is that of Clever Hans, a horse in early twentieth-century Germany that appeared to solve arithmetic problems by tapping its hoof the correct number of times. Careful testing eventually revealed that Hans was not calculating at all; instead, he was responding to tiny, unconscious changes in the posture and expression of the people around him, stopping when they relaxed. The episode is still used to warn against anthropomorphism — the tendency to assume that animals think in exactly the same way as humans. Modern experiments are therefore designed with strict controls to rule out such hidden influences.

F    Despite these cautions, the broader conclusion is difficult to dismiss. Across very different species — insects, birds, and mammals — animals display abilities that go well beyond simple reflex. They can communicate detailed information, plan for future needs, and adjust their behaviour to changing circumstances. Understanding these capacities also has practical consequences, influencing debates about animal welfare and the conditions in which animals are kept in farms, laboratories, and zoos. For many researchers, the central question is no longer whether animals think, but how their minds differ from our own.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 2, 1, 'Karl von Frisch spent many years studying how honeybees communicate.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 3, 1, 'The angle of the waggle dance shows how far away food is located.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 4, 1, 'Vervet monkeys'' alarm calls only express fear and convey no specific information.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 5, 1, 'New Caledonian crows live longer than most other bird species.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NOT GIVEN', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 6, 1, 'Paragraph C', NULL, '[{"label": "i", "text": "The risk of seeing human qualities in animals"}, {"label": "ii", "text": "How insects find their way home"}, {"label": "iii", "text": "Evidence of planning through the use of tools"}, {"label": "iv", "text": "Why some species cannot be trained"}, {"label": "v", "text": "Remembering the details of past events"}, {"label": "vi", "text": "Wide-ranging skills and their practical significance"}, {"label": "vii", "text": "The dangers animals face from predators"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 7, 1, 'Paragraph D', NULL, '[{"label": "i", "text": "The risk of seeing human qualities in animals"}, {"label": "ii", "text": "How insects find their way home"}, {"label": "iii", "text": "Evidence of planning through the use of tools"}, {"label": "iv", "text": "Why some species cannot be trained"}, {"label": "v", "text": "Remembering the details of past events"}, {"label": "vi", "text": "Wide-ranging skills and their practical significance"}, {"label": "vii", "text": "The dangers animals face from predators"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 8, 1, 'Paragraph E', NULL, '[{"label": "i", "text": "The risk of seeing human qualities in animals"}, {"label": "ii", "text": "How insects find their way home"}, {"label": "iii", "text": "Evidence of planning through the use of tools"}, {"label": "iv", "text": "Why some species cannot be trained"}, {"label": "v", "text": "Remembering the details of past events"}, {"label": "vi", "text": "Wide-ranging skills and their practical significance"}, {"label": "vii", "text": "The dangers animals face from predators"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 9, 1, 'Paragraph F', NULL, '[{"label": "i", "text": "The risk of seeing human qualities in animals"}, {"label": "ii", "text": "How insects find their way home"}, {"label": "iii", "text": "Evidence of planning through the use of tools"}, {"label": "iv", "text": "Why some species cannot be trained"}, {"label": "v", "text": "Remembering the details of past events"}, {"label": "vi", "text": "Wide-ranging skills and their practical significance"}, {"label": "vii", "text": "The dangers animals face from predators"}]'::jsonb, 'vi', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 10, 1, 'The duration of a honeybee''s dance indicates the ______ of a food source.', NULL, NULL, 'distance', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 11, 1, 'In one experiment, Betty used a hook to lift a bucket of food out of a ______.', NULL, NULL, 'tube', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 12, 1, '______ items such as insects are recovered by scrub jays before they spoil.', NULL, NULL, 'Perishable/perishable', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 13, 1, 'The case of Clever Hans is used to caution scientists against ______.', NULL, NULL, 'anthropomorphism', 'sentence_completion');
