-- MT2 Reading content alignment — founder source (P1 completion, P2 TFNG/headings/completion + 6-para passage, P3 unchanged).
-- mock_test_id = a0000000-0000-4000-8000-000000000002

-- BandForge reading seed: How Animals Make Sense of Their World
-- mock_test_id = a0000000-0000-4000-8000-000000000002 part = 1

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 1
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 1;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 1, 1, 'Scientists once believed that intelligent-looking animal behaviour was caused by instinct.', 'How Animals Make Sense of Their World

A    During much of the twentieth century, scientists were reluctant to credit animals with anything resembling thought. Behaviour that appeared intelligent was usually explained as instinct — fixed responses shaped by evolution rather than genuine reasoning. A barking dog or a nest-building bird was seen as following an inherited programme, not making a decision. This cautious view has gradually given way to a more generous picture. The field known as animal cognition now studies how creatures perceive, remember, and respond to the world around them, drawing on careful observation in the wild as well as controlled laboratory experiments. A growing body of evidence suggests that many species process information in surprisingly flexible ways. Researchers are careful, however, to distinguish between behaviour that merely looks clever and behaviour that genuinely involves understanding, since the two can be difficult to tell apart.

B    Communication has provided some of the most striking examples of this flexibility. The Austrian zoologist Karl von Frisch spent decades decoding the so-called waggle dance of honeybees, a looping movement performed inside the hive that conveys both the direction and the distance of a food source. The angle of the dance indicates direction relative to the sun, while its duration signals how far away the food lies. His work was so influential that he shared the Nobel Prize in 1973. Many years later, the researchers Robert Seyfarth and Dorothy Cheney studied vervet monkeys in East Africa and showed that they use distinct alarm calls for different predators. One sound sends the group climbing into the trees to escape leopards, while another makes them look upward to watch for eagles. The calls function almost like words, each tied to a specific meaning rather than simply expressing fear.

C    Problem-solving offers further evidence of mental flexibility. New Caledonian crows are perhaps the best-studied example. In the wild they shape twigs and leaves into hooks to extract insects from narrow crevices, and in laboratory tests they have solved multi-step puzzles that require using one tool to obtain another. In one widely reported experiment, a captive crow named Betty bent a straight piece of wire into a hook in order to lift a small bucket of food out of a tube — a solution she had never been trained to produce. Although later studies showed that wild crows also bend materials naturally, the birds'' ability to adapt their methods to new situations remains impressive. Such behaviour suggests that they can picture a goal and work out the sequence of steps needed to reach it.

D    Memory, too, can be remarkably sophisticated. Western scrub jays hide thousands of food items across their territory and later recover them with considerable accuracy. Research led by Nicola Clayton at the University of Cambridge demonstrated that these birds remember not only where they stored food but also what they stored and how long ago they did so. Perishable items such as insects are retrieved before they have time to spoil, while longer-lasting seeds may be left for several days. The jays even appear to change their hiding behaviour when other birds are watching, returning later to move the food to a new location. This ability to keep track of specific past events was once thought to be unique to humans.

E    Not every impressive performance withstands close scrutiny, and scientists remain wary of reading too much into animal behaviour. The most famous cautionary tale is that of Clever Hans, a horse in early twentieth-century Germany that appeared to solve arithmetic problems by tapping its hoof the correct number of times. Careful testing eventually revealed that Hans was not calculating at all; instead, he was responding to tiny, unconscious changes in the posture and expression of the people around him, stopping when they relaxed. The episode is still used to warn against anthropomorphism — the tendency to assume that animals think in exactly the same way as humans. Modern experiments are therefore designed with strict controls to rule out such hidden influences.

F    Despite growing evidence for animal cognition, drawing firm conclusions remains difficult. A behaviour that looks thoughtful in one setting may have a simpler explanation in another, and scientists therefore hesitate to attribute human-like understanding without rigorous proof. Nevertheless, the findings already have practical implications. Many mammals display social awareness and adjust their behaviour to circumstances in ways that challenge old assumptions about mindless instinct. How humans house, train, and study animals on farms, in laboratories, and in zoos is increasingly shaped by these questions. Researchers stress, however, that respecting animal welfare is not the same as claiming animals reason exactly as people do.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 2, 1, 'Karl von Frisch demonstrated that the honeybee waggle dance indicates direction and distance.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 3, 1, 'Vervet monkeys use the same alarm call for every predator.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 4, 1, 'Betty the crow had been trained to bend wire before the experiment.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 5, 1, 'Western scrub jays remember when as well as where they hid food.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 6, 1, 'Paragraph C', NULL, '[{"label": "i", "text": "Replacing earlier scepticism with a new field of study"}, {"label": "ii", "text": "How animals communicate with each other"}, {"label": "iii", "text": "Evidence of planning in tool use"}, {"label": "iv", "text": "Remembering where food was hidden"}, {"label": "v", "text": "A famous case of mistaken intelligence"}, {"label": "vi", "text": "Practical implications for how animals are treated"}, {"label": "vii", "text": "Why laboratory conditions are essential"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 7, 1, 'Paragraph D', NULL, '[{"label": "i", "text": "Replacing earlier scepticism with a new field of study"}, {"label": "ii", "text": "How animals communicate with each other"}, {"label": "iii", "text": "Evidence of planning in tool use"}, {"label": "iv", "text": "Remembering where food was hidden"}, {"label": "v", "text": "A famous case of mistaken intelligence"}, {"label": "vi", "text": "Practical implications for how animals are treated"}, {"label": "vii", "text": "Why laboratory conditions are essential"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 8, 1, 'Paragraph E', NULL, '[{"label": "i", "text": "Replacing earlier scepticism with a new field of study"}, {"label": "ii", "text": "How animals communicate with each other"}, {"label": "iii", "text": "Evidence of planning in tool use"}, {"label": "iv", "text": "Remembering where food was hidden"}, {"label": "v", "text": "A famous case of mistaken intelligence"}, {"label": "vi", "text": "Practical implications for how animals are treated"}, {"label": "vii", "text": "Why laboratory conditions are essential"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 9, 1, 'Paragraph F', NULL, '[{"label": "i", "text": "Replacing earlier scepticism with a new field of study"}, {"label": "ii", "text": "How animals communicate with each other"}, {"label": "iii", "text": "Evidence of planning in tool use"}, {"label": "iv", "text": "Remembering where food was hidden"}, {"label": "v", "text": "A famous case of mistaken intelligence"}, {"label": "vi", "text": "Practical implications for how animals are treated"}, {"label": "vii", "text": "Why laboratory conditions are essential"}]'::jsonb, 'vi', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 10, 1, 'The duration of a honeybee''s dance indicates the ______ of a food source.', NULL, NULL, 'distance', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 11, 1, 'In one experiment, Betty used a hook to lift a bucket of food out of a ______.', NULL, NULL, 'tube', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 12, 1, '______ items such as insects are recovered by scrub jays before they spoil.', NULL, NULL, 'Perishable/perishable', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 13, 1, 'The case of Clever Hans is used to caution scientists against ______.', NULL, NULL, 'anthropomorphism', 'sentence_completion');
-- BandForge reading seed: The Unfulfilled Promise of Educational Technology
-- mock_test_id = a0000000-0000-4000-8000-000000000002 part = 2

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 2
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 2;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 1, 2, 'Predictions that new technologies would transform education have a long history.', 'The Unfulfilled Promise of Educational Technology

A    For more than a century, each new communication technology has arrived in classrooms accompanied by bold predictions. In the 1920s, the inventor Thomas Edison declared that motion pictures would soon replace textbooks; later, radio, television, and the personal computer were each described as forces that would transform how children learn. The pattern has been remarkably consistent: an initial wave of enthusiasm, followed by disappointment as the new tool fails to deliver the promised revolution. Understanding why this cycle repeats has become an important question for researchers, particularly as digital devices now occupy a central place in schools worldwide. The mismatch between confident forecasts and actual classroom results raises a deeper issue: whether the problem lies in the technology itself, or in the assumptions made about what it can achieve.

B    The most recent example of this cycle is the massive open online course, or MOOC. When platforms such as Coursera and edX were launched in 2012, commentators described that period as the "year of the MOOC" and predicted that free, university-level courses would make traditional institutions obsolete. Enrolment figures were indeed enormous, with individual courses attracting hundreds of thousands of registrations. Yet completion told a different story. A widely cited analysis by researchers at the University of Pennsylvania found that, on average, only about four per cent of those who signed up for a course finished it. Most participants, moreover, already held a degree, suggesting that the courses were extending opportunity for the well-educated rather than reaching new learners. By the end of the decade, most universities had quietly accepted that MOOCs would complement campus teaching rather than replace it.

C    Similar gaps between expectation and outcome have appeared in schools. Many governments have invested heavily in schemes to provide every pupil with a laptop or tablet, on the assumption that access to devices would automatically raise achievement. The evidence has been mixed at best. A large 2015 report by the Organisation for Economic Co-operation and Development examined data from dozens of countries and concluded that students who used computers very frequently at school tended to perform worse in reading and mathematics, even after social background was taken into account. The report did not argue that technology was harmful in itself, but it questioned the belief that simply distributing hardware would improve results. What mattered, the authors suggested, was not whether computers were present but how, and how often, they were used.

D    Researchers who study these failures point to a recurring misunderstanding. Technology, they argue, is not a substitute for skilled teaching; it is a tool whose value depends entirely on how it is used. A tablet can display an excellent lesson or a poor one, and a pupil left alone with a device may simply become distracted. There is also evidence of a so-called second digital divide. While access to devices has become more equal, the ability to use them productively has not. Students from advantaged homes are more likely to use technology for learning, whereas those from poorer backgrounds more often use the same devices for entertainment, which can widen rather than narrow existing gaps in attainment.

E    None of this means that technology has no place in education. When it is carefully designed and closely integrated with teaching, it can produce genuine benefits. Adaptive learning software, which adjusts the difficulty of questions to each learner''s performance, has shown modest but consistent gains in subjects such as mathematics. The underlying idea is old: in 1984 the psychologist Benjamin Bloom observed that a student receiving one-to-one tutoring could outperform around ninety-eight per cent of pupils taught in conventional classes, a result he called the "two sigma problem". Personalised software cannot fully reproduce a human tutor, but it can offer some of the individual attention that large classes make impossible.

F    Crucially, the most successful programmes are not those that replace teachers but those that support them — adjusting content while keeping a human adult in charge of motivation and discipline. As long as schools focus narrowly on hardware adoption rather than on training teachers to use tools well, the cycle of promise and disappointment is likely to continue.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 2, 2, 'Individual MOOCs were able to attract very large numbers of registrations.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 3, 2, 'The University of Pennsylvania study found that the majority of MOOC enrollees completed their course.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 4, 2, 'The 2015 OECD report concluded that computers are inherently harmful to learning.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 5, 2, 'Adaptive learning software is now used in most secondary schools.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NOT GIVEN', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 6, 2, 'Paragraph C', NULL, '[{"label": "i", "text": "Hardware alone does not guarantee better results"}, {"label": "ii", "text": "The high cost of modern classroom devices"}, {"label": "iii", "text": "How a lack of understanding limits technology''s value"}, {"label": "iv", "text": "Software that responds to the individual learner"}, {"label": "v", "text": "Technology as a partner to good teaching"}, {"label": "vi", "text": "The decline of the traditional university"}, {"label": "vii", "text": "Why online courses attract so many students"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 7, 2, 'Paragraph D', NULL, '[{"label": "i", "text": "Hardware alone does not guarantee better results"}, {"label": "ii", "text": "The high cost of modern classroom devices"}, {"label": "iii", "text": "How a lack of understanding limits technology''s value"}, {"label": "iv", "text": "Software that responds to the individual learner"}, {"label": "v", "text": "Technology as a partner to good teaching"}, {"label": "vi", "text": "The decline of the traditional university"}, {"label": "vii", "text": "Why online courses attract so many students"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 8, 2, 'Paragraph E', NULL, '[{"label": "i", "text": "Hardware alone does not guarantee better results"}, {"label": "ii", "text": "The high cost of modern classroom devices"}, {"label": "iii", "text": "How a lack of understanding limits technology''s value"}, {"label": "iv", "text": "Software that responds to the individual learner"}, {"label": "v", "text": "Technology as a partner to good teaching"}, {"label": "vi", "text": "The decline of the traditional university"}, {"label": "vii", "text": "Why online courses attract so many students"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 9, 2, 'Paragraph F', NULL, '[{"label": "i", "text": "Hardware alone does not guarantee better results"}, {"label": "ii", "text": "The high cost of modern classroom devices"}, {"label": "iii", "text": "How a lack of understanding limits technology''s value"}, {"label": "iv", "text": "Software that responds to the individual learner"}, {"label": "v", "text": "Technology as a partner to good teaching"}, {"label": "vi", "text": "The decline of the traditional university"}, {"label": "vii", "text": "Why online courses attract so many students"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 10, 2, 'Commentators described the period when Coursera and edX launched as the ______ of the MOOC.', NULL, NULL, 'year', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 11, 2, 'The University of Pennsylvania analysis found that only about ______ of enrollees completed their courses.', NULL, NULL, 'four per cent/4 per cent/four percent/4 percent', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 12, 2, 'Students who used computers very frequently at school often performed ______ in reading and mathematics.', NULL, NULL, 'worse', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 13, 2, 'Bloom described the tutoring gap as the ______ problem.', NULL, NULL, 'two sigma', 'sentence_completion');
-- BandForge reading seed: The Psychology of Leadership in Times of Crisis
-- mock_test_id = a0000000-0000-4000-8000-000000000002 part = 3

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 3
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 3;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 1, 3, 'Citizens always form an accurate picture of their leaders during a crisis.', 'The Psychology of Leadership in Times of Crisis

A    When a nation faces sudden danger — a war, an economic collapse, a pandemic — public attention turns sharply towards those in charge. Citizens expect their leaders to act with clarity and resolve, and historians often judge a presidency or premiership by its conduct during such moments. Yet the psychological reality of leading under crisis is considerably more complicated than the popular image of the calm, all-seeing decision-maker suggests. Crises do not merely test character; they distort the conditions under which judgement is exercised, compressing the time available for reflection and raising the stakes of every choice. Understanding how leaders actually behave under such pressure has therefore become a significant concern for political psychologists. Their work draws on historical case studies, interviews, and controlled experiments, and it consistently challenges the assumption that good leadership in a crisis is simply a matter of strength of will.

B    One of the most consistent findings is that acute stress narrows the range of options a leader is able to consider. Under pressure, decision-making tends to become faster but also more rigid, with individuals relying on familiar assumptions rather than seeking fresh information. This tendency is intensified within small groups of advisers. In 1972 the psychologist Irving Janis introduced the term "groupthink" to describe how cohesive teams, anxious to preserve unity, can suppress dissent and converge prematurely on a flawed course of action. His central example was the 1961 decision by the United States government to support an invasion of Cuba at the Bay of Pigs — a plan whose obvious weaknesses went unchallenged because no adviser wished to appear disloyal. Janis argued that the problem was not a lack of intelligence among those involved, but a social atmosphere in which doubt felt inappropriate.

C    Crisis leadership is not only a matter of private decision-making; it is also, perhaps above all, an exercise in public communication. A leader''s words can either steady a frightened population or deepen its alarm. Research into political rhetoric suggests that audiences respond less to the technical content of a message than to the impression of competence and sincerity it conveys. During the economic emergency of the 1930s, the broadcasts of the American president Franklin Roosevelt were widely credited with restoring public confidence, not because they offered detailed policy but because they projected steadiness and candour. The lesson drawn by later scholars was that the management of emotion is as central to crisis leadership as the management of events.

D    A more troubling pattern concerns the projection of certainty. Because populations crave reassurance, leaders are rewarded for appearing confident, even when the situation is genuinely unclear. This creates an incentive to overstate what is known and to understate what is not. The political scientist Philip Tetlock, in a long study of expert forecasting, found that confident, decisive predictions were no more accurate than cautious ones — and were often less so — yet they consistently attracted more attention and trust. Applied to crisis leadership, this finding implies a hidden cost: the very assurance that calms the public in the short term may discourage the honest revision of policy when circumstances change.

E    It is tempting to assume that emergencies reveal a leader''s "true self", or even that they create new qualities under pressure. The evidence points instead to amplification. Crises rarely transform personality; more often they exaggerate dispositions that were already present. A leader inclined towards caution becomes more hesitant, while one prone to boldness becomes more reckless. For this reason, psychologists who study political behaviour place considerable weight on a leader''s record before a crisis arrives, treating it as a better guide to likely conduct than any promise made once danger is at hand. This is one reason why sudden shifts in a leader''s behaviour during a crisis are often viewed by researchers with scepticism rather than admiration.', '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 2, 3, 'Stress makes leaders consider a wider range of options.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 3, 3, 'Groupthink was first described using the Bay of Pigs invasion as an example.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'YES', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 4, 3, 'Roosevelt''s broadcasts succeeded because they explained policy in technical detail.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 5, 3, 'Tetlock found that confident forecasts were usually more accurate.', NULL, '[{"label": "YES", "text": "YES"}, {"label": "NO", "text": "NO"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NO', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 6, 3, 'Paragraph B', NULL, '[{"label": "i", "text": "How stress alters private decision-making"}, {"label": "ii", "text": "Why advisers may fail to challenge a leader"}, {"label": "iii", "text": "The role of public speaking during emergencies"}, {"label": "iv", "text": "The temptation to appear more certain than the facts allow"}, {"label": "v", "text": "Why earlier behaviour may predict crisis conduct"}, {"label": "vi", "text": "The advantages of calm leadership"}, {"label": "vii", "text": "How historians judge failed policies"}]'::jsonb, 'i', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 7, 3, 'Paragraph C', NULL, '[{"label": "i", "text": "How stress alters private decision-making"}, {"label": "ii", "text": "Why advisers may fail to challenge a leader"}, {"label": "iii", "text": "The role of public speaking during emergencies"}, {"label": "iv", "text": "The temptation to appear more certain than the facts allow"}, {"label": "v", "text": "Why earlier behaviour may predict crisis conduct"}, {"label": "vi", "text": "The advantages of calm leadership"}, {"label": "vii", "text": "How historians judge failed policies"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 8, 3, 'Paragraph D', NULL, '[{"label": "i", "text": "How stress alters private decision-making"}, {"label": "ii", "text": "Why advisers may fail to challenge a leader"}, {"label": "iii", "text": "The role of public speaking during emergencies"}, {"label": "iv", "text": "The temptation to appear more certain than the facts allow"}, {"label": "v", "text": "Why earlier behaviour may predict crisis conduct"}, {"label": "vi", "text": "The advantages of calm leadership"}, {"label": "vii", "text": "How historians judge failed policies"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 9, 3, 'Paragraph E', NULL, '[{"label": "i", "text": "How stress alters private decision-making"}, {"label": "ii", "text": "Why advisers may fail to challenge a leader"}, {"label": "iii", "text": "The role of public speaking during emergencies"}, {"label": "iv", "text": "The temptation to appear more certain than the facts allow"}, {"label": "v", "text": "Why earlier behaviour may predict crisis conduct"}, {"label": "vi", "text": "The advantages of calm leadership"}, {"label": "vii", "text": "How historians judge failed policies"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 10, 3, 'Irving Janis introduced the term ______ in 1972.', NULL, NULL, 'groupthink', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 11, 3, 'During the 1930s, ______ broadcast to restore public confidence.', NULL, NULL, 'Roosevelt/Franklin Roosevelt', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 12, 3, 'Tetlock found that bold predictions attracted more ______.', NULL, NULL, 'trust/attention', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 13, 3, 'Crises tend to ______ existing personality traits.', NULL, NULL, 'amplify/exaggerate', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 14, 3, 'Sudden changes in a leader''s behaviour are often viewed with ______.', NULL, NULL, 'scepticism/skepticism', 'sentence_completion');
