-- BandForge reading seed: How Animals Make Sense of Their World
-- mock_test_id = a0000000-0000-4000-8000-000000000002 part = 1

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 1
);
DELETE FROM questions WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000002' AND module = 'reading' AND part = 1;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 1, 1, 'Scientists once believed that intelligent-looking animal behaviour was caused by instinct.', 'How Animals Make Sense of Their World

A    During much of the twentieth century, scientists were reluctant to credit animals with anything resembling thought. Behaviour that appeared intelligent was usually explained as instinct — fixed responses shaped by evolution rather than genuine reasoning. A barking dog or a nest-building bird was seen as following an inherited programme, not making a decision. This cautious view has gradually given way to a more generous picture. The field known as animal cognition now studies how creatures perceive, remember, and respond to the world around them, drawing on careful observation in the wild as well as controlled laboratory experiments. A growing body of evidence suggests that many species process information in surprisingly flexible ways. Researchers are careful, however, to distinguish between behaviour that merely looks clever and behaviour that genuinely involves understanding, since the two can be difficult to tell apart.

B    Communication has provided some of the most striking examples of this flexibility. The Austrian zoologist Karl von Frisch spent decades decoding the so-called waggle dance of honeybees, a looping movement performed inside the hive that conveys both the direction and the distance of a food source. The angle of the dance indicates direction relative to the sun, while its duration signals how far away the food lies. His work was so influential that he shared the Nobel Prize in 1973. Many years later, the researchers Robert Seyfarth and Dorothy Cheney studied vervet monkeys in East Africa and showed that they use distinct alarm calls for different predators. One sound sends the group climbing into the trees to escape leopards, while another makes them look upward to watch for eagles. The calls function almost like words, each tied to a specific meaning rather than simply expressing fear.

C    Problem-solving offers further evidence of mental flexibility. New Caledonian crows are perhaps the best-studied example. In the wild they shape twigs and leaves into hooks to extract insects from narrow crevices, and in laboratory tests they have solved multi-step puzzles that require using one tool to obtain another. In one widely reported experiment, a captive crow named Betty bent a straight piece of wire into a hook in order to lift a small bucket of food out of a tube — a solution she had never been trained to produce. Although later studies showed that wild crows also bend materials naturally, the birds'' ability to adapt their methods to new situations remains impressive. Such behaviour suggests that they can picture a goal and work out the sequence of steps needed to reach it.

D    Memory, too, can be remarkably sophisticated. Western scrub jays hide thousands of food items across their territory and later recover them with considerable accuracy. Research led by Nicola Clayton at the University of Cambridge demonstrated that these birds remember not only where they stored food but also what they stored and how long ago they did so. Perishable items such as insects are retrieved before they have time to spoil, while longer-lasting seeds may be left for several days. The jays even appear to change their hiding behaviour when other birds are watching, returning later to move the food to a new location. This ability to keep track of specific past events was once thought to be unique to humans.

E    Not every impressive performance withstands close scrutiny, and scientists remain wary of reading too much into animal behaviour. The most famous cautionary tale is that of Clever Hans, a horse in early twentieth-century Germany that appeared to solve arithmetic problems by tapping its hoof the correct number of times. Careful testing eventually revealed that Hans was not calculating at all; instead, he was responding to tiny, unconscious changes in the posture and expression of the people around him, stopping when they relaxed. The episode is still used to warn against anthropomorphism — the tendency to assume that animals think in exactly the same way as humans. Modern experiments are therefore designed with strict controls to rule out such hidden influences.

F    Despite growing evidence for animal cognition, drawing firm conclusions remains difficult. A behaviour that looks thoughtful in one setting may have a simpler explanation in another, and scientists therefore hesitate to attribute human-like understanding without rigorous proof. Nevertheless, the findings already have practical implications. Many mammals display social awareness and adjust their behaviour to circumstances in ways that challenge old assumptions about mindless instinct. How humans house, train, and study animals on farms, in laboratories, and in zoos is increasingly shaped by these questions. Researchers stress, however, that respecting animal welfare is not the same as claiming animals reason exactly as people do.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 2, 1, 'Karl von Frisch demonstrated that the honeybee waggle dance indicates direction and distance.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 3, 1, 'Vervet monkeys use the same alarm call for every predator.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 4, 1, 'Betty the crow had been trained to bend wire before the experiment.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'tfng', 5, 1, 'Western scrub jays remember when as well as where they hid food.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 6, 1, 'Paragraph C', NULL, '[{"label": "i", "text": "Replacing earlier scepticism with a new field of study"}, {"label": "ii", "text": "How animals communicate with each other"}, {"label": "iii", "text": "Evidence of planning in tool use"}, {"label": "iv", "text": "Remembering where food was hidden"}, {"label": "v", "text": "A famous case of mistaken intelligence"}, {"label": "vi", "text": "Practical implications for how animals are treated"}, {"label": "vii", "text": "Why laboratory conditions are essential"}]'::jsonb, 'iii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 7, 1, 'Paragraph D', NULL, '[{"label": "i", "text": "Replacing earlier scepticism with a new field of study"}, {"label": "ii", "text": "How animals communicate with each other"}, {"label": "iii", "text": "Evidence of planning in tool use"}, {"label": "iv", "text": "Remembering where food was hidden"}, {"label": "v", "text": "A famous case of mistaken intelligence"}, {"label": "vi", "text": "Practical implications for how animals are treated"}, {"label": "vii", "text": "Why laboratory conditions are essential"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 8, 1, 'Paragraph E', NULL, '[{"label": "i", "text": "Replacing earlier scepticism with a new field of study"}, {"label": "ii", "text": "How animals communicate with each other"}, {"label": "iii", "text": "Evidence of planning in tool use"}, {"label": "iv", "text": "Remembering where food was hidden"}, {"label": "v", "text": "A famous case of mistaken intelligence"}, {"label": "vi", "text": "Practical implications for how animals are treated"}, {"label": "vii", "text": "Why laboratory conditions are essential"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'matching_headings', 9, 1, 'Paragraph F', NULL, '[{"label": "i", "text": "Replacing earlier scepticism with a new field of study"}, {"label": "ii", "text": "How animals communicate with each other"}, {"label": "iii", "text": "Evidence of planning in tool use"}, {"label": "iv", "text": "Remembering where food was hidden"}, {"label": "v", "text": "A famous case of mistaken intelligence"}, {"label": "vi", "text": "Practical implications for how animals are treated"}, {"label": "vii", "text": "Why laboratory conditions are essential"}]'::jsonb, 'vi', 'matching_headings'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 10, 1, 'Karl von Frisch spent ______ decoding the waggle dance of honeybees.', NULL, NULL, 'decades', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 11, 1, 'Betty bent a straight piece of ______ into a hook.', NULL, NULL, 'wire', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 12, 1, 'Scrub jays may move food when other birds are ______.', NULL, NULL, 'watching', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000002', 'reading', 'sentence_completion', 13, 1, 'Clever Hans responded to changes in people''s ______.', NULL, NULL, 'posture/expression/posture and expression', 'sentence_completion');
