-- M01 Reading Passage 1: The Hidden Forces Behind Everyday Choices (examiner pack, word-for-word)
-- Source: test/reading/source/Reading Task 2.pages

DELETE FROM answers WHERE question_id IN (
  SELECT id FROM questions
  WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000001'
    AND module = 'reading'
    AND part = 1
);

DELETE FROM questions
WHERE mock_test_id = 'a0000000-0000-4000-8000-000000000001'
  AND module = 'reading'
  AND part = 1;

INSERT INTO questions (
  mock_test_id, module, question_type, question_number, part, prompt,
  passage_text, options, correct_answer, skill_tag
) VALUES
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 1, 1, 'Economic models built around homo economicus were valued for their mathematical convenience.', 'The Hidden Forces Behind Everyday Choices

A    For much of the twentieth century, economic theory rested on a confident assumption: that people behave as rational agents, weighing costs and benefits with cool precision before arriving at the choice that best serves their interests. This figure, often called homo economicus, was a useful simplification for building mathematical models, but it bore little resemblance to the messy reality of human behaviour. The field of behavioural economics emerged to close that gap, drawing on psychology to explain why ordinary consumers so often act in ways that conventional theory cannot predict.

B    The most influential challenge to the rational model came from psychologists Daniel Kahneman and Amos Tversky, whose research in the 1970s and 1980s reshaped the discipline. Their prospect theory demonstrated that people do not evaluate gains and losses symmetrically. Instead, the pain of losing a sum of money is felt roughly twice as intensely as the pleasure of gaining the same amount — a phenomenon known as loss aversion. This asymmetry helps explain a range of puzzling behaviours, from investors who cling to failing shares rather than accept a loss, to shoppers who respond far more strongly to the threat of a price increase than to an equivalent discount.

C    A second well-documented bias is anchoring, the tendency for an initial piece of information to exert a disproportionate influence on subsequent judgements. When a retailer displays a high "original" price beside a reduced one, the first figure functions as an anchor, making the discount appear more generous than it might otherwise seem. Anchors operate even when they are plainly arbitrary; experiments have shown that a number generated at random can shift people''s estimates of entirely unrelated quantities. For the consumer, this means that the order in which information is presented can quietly determine what feels like a fair price.

D    Perhaps the most counterintuitive finding concerns the effect of abundant choice. Classical economics holds that more options can only make consumers better off, since unwanted alternatives can simply be ignored. Yet a celebrated study by Sheena Iyengar and Mark Lepper suggested otherwise. In a supermarket, the researchers set up a tasting display offering either six varieties of jam or twenty-four. The larger array attracted more passing interest, but it was the smaller selection that produced sales: only three per cent of shoppers who saw the extensive display made a purchase, compared with thirty per cent of those presented with the limited one. Excessive choice, it appeared, could overwhelm rather than empower.

E    Closely related is the power of defaults — the option that applies when a person makes no active decision at all. Because changing a default requires effort and deliberate attention, most people simply accept whatever has been set for them. The clearest demonstration comes from research by Eric Johnson and Daniel Goldstein on organ donation. In countries where citizens are registered as donors unless they opt out, participation rates exceed ninety per cent; in otherwise similar countries where citizens must opt in, rates often fall below twenty per cent. The decision itself has not changed, only the default — yet the outcome is transformed.

F    These insights have given rise to the concept of the "nudge", popularised by economist Richard Thaler and legal scholar Cass Sunstein. A nudge is any feature of the environment that steers behaviour in a predictable direction without forbidding alternatives or significantly altering incentives. Placing fruit at eye level in a cafeteria is a nudge; banning chocolate is not. The approach, which its authors term libertarian paternalism, has been adopted by governments and businesses worldwide. It is not without critics, however. Some argue that nudges exploit the very weaknesses they identify, manipulating consumers rather than informing them, and that the line between gentle guidance and covert pressure is uncomfortably thin.

G    What is no longer in dispute is that the rational consumer of classical theory was always a fiction. Decisions are shaped by context, framing, emotion and effort in ways that are systematic and, crucially, predictable. For firms, this knowledge is commercially valuable, and the techniques of behavioural economics are now embedded in everything from website design to supermarket layouts. The asymmetry of knowledge between the designer of a choice and the person making it has become, for some scholars, a question of fairness as much as of economics. For consumers, the lesson is more sobering: the environment in which a choice is made is rarely neutral, and understanding the hidden forces at work may be the first step towards resisting them.', '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 2, 1, 'According to prospect theory, losing a sum of money causes roughly twice as much distress as gaining the same sum brings satisfaction.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'TRUE', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 3, 1, 'Anchoring affects consumer judgement only when the initial figure is a realistic price.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 4, 1, 'The display of twenty-four jams attracted less interest from passers-by than the display of six.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'FALSE', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'tfng', 5, 1, 'The organ donation research found that opt-out countries also have higher overall life expectancy.', NULL, '[{"label": "TRUE", "text": "TRUE"}, {"label": "FALSE", "text": "FALSE"}, {"label": "NOT GIVEN", "text": "NOT GIVEN"}]'::jsonb, 'NOT GIVEN', 'tfng'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'matching_headings', 6, 1, 'Paragraph C', NULL, '[{"label": "i", "text": "The mathematical origins of consumer theory"}, {"label": "ii", "text": "The lasting pull of a first impression"}, {"label": "iii", "text": "Why losses outweigh gains"}, {"label": "iv", "text": "When greater variety discourages purchasing"}, {"label": "v", "text": "The influence of the option requiring no action"}, {"label": "vi", "text": "Guiding behaviour without removing freedom"}, {"label": "vii", "text": "The commercial uses of behavioural research"}]'::jsonb, 'ii', 'matching_headings'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'matching_headings', 7, 1, 'Paragraph D', NULL, '[{"label": "i", "text": "The mathematical origins of consumer theory"}, {"label": "ii", "text": "The lasting pull of a first impression"}, {"label": "iii", "text": "Why losses outweigh gains"}, {"label": "iv", "text": "When greater variety discourages purchasing"}, {"label": "v", "text": "The influence of the option requiring no action"}, {"label": "vi", "text": "Guiding behaviour without removing freedom"}, {"label": "vii", "text": "The commercial uses of behavioural research"}]'::jsonb, 'iv', 'matching_headings'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'matching_headings', 8, 1, 'Paragraph E', NULL, '[{"label": "i", "text": "The mathematical origins of consumer theory"}, {"label": "ii", "text": "The lasting pull of a first impression"}, {"label": "iii", "text": "Why losses outweigh gains"}, {"label": "iv", "text": "When greater variety discourages purchasing"}, {"label": "v", "text": "The influence of the option requiring no action"}, {"label": "vi", "text": "Guiding behaviour without removing freedom"}, {"label": "vii", "text": "The commercial uses of behavioural research"}]'::jsonb, 'v', 'matching_headings'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'matching_headings', 9, 1, 'Paragraph F', NULL, '[{"label": "i", "text": "The mathematical origins of consumer theory"}, {"label": "ii", "text": "The lasting pull of a first impression"}, {"label": "iii", "text": "Why losses outweigh gains"}, {"label": "iv", "text": "When greater variety discourages purchasing"}, {"label": "v", "text": "The influence of the option requiring no action"}, {"label": "vi", "text": "Guiding behaviour without removing freedom"}, {"label": "vii", "text": "The commercial uses of behavioural research"}]'::jsonb, 'vi', 'matching_headings'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'sentence_completion', 10, 1, 'Choosing not to accept a preset option demands both effort and deliberate ______.', NULL, NULL, 'attention', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'sentence_completion', 11, 1, 'Thaler and Sunstein describe the philosophy behind the nudge as ______.', NULL, NULL, 'libertarian paternalism/libertarian', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'sentence_completion', 12, 1, 'Critics suggest that the boundary between gentle guidance and ______ is uncomfortably thin.', NULL, NULL, 'covert pressure', 'sentence_completion'),
('a0000000-0000-4000-8000-000000000001', 'reading', 'sentence_completion', 13, 1, 'The techniques of behavioural economics are now used in areas ranging from supermarket layouts to ______.', NULL, NULL, 'website design', 'sentence_completion');
